<?php

abstract class AbstractObject {
    protected $backend_instance = null;
    protected $generate_subpath = 'nagios';
    protected $generate_filename = null;
    protected $exported = array();
    protected $fp = null;
    
    protected $attributes_write = array();
    protected $attributes_array = array();
    protected $attributes_hash = array();
    protected $attributes_default = array();

    public static function getInstance() {
        static $instances = array();

        $calledClass = get_called_class();

        if (!isset($instances[$calledClass])) {
            $instances[$calledClass] = new $calledClass();
        }

        return $instances[$calledClass];
    }
    
    protected function __construct() {
        $this->backend_instance = Backend::getInstance();
    }
    
    public function close_file() {
        if (!is_null($this->fp)) {
            fclose($this->fp);
        }
        $this->fp = null;
    }
    
    public function reset() {
        $this->close_file();
        $this->exported = array();
        $this->createFile($this->backend_instance->getPath());
    }
    
    private function setHeader() {
        $header = 
"###################################################################\n" .
"#                                                                 #\n" .
"#                       GENERATED BY CENTREON                     #\n" .
"#                                                                 #\n" . 
"#               Developped by :                                   #\n" .
"#                   - Julien Mathis                               #\n" .
"#                   - Romain Le Merlus                            #\n" .
"#                                                                 #\n" .
"#                           www.centreon.com                      #\n" .
"#                For information : contact@centreon.com           #\n" .
"###################################################################\n" .
"#                                                                 #\n" .
"#         Last modification " . sprintf("%-38s#\n", date('Y-m-d H:i')) . 
"#         By " . sprintf("%-53s#\n", $this->backend_instance->getUserName()) .
"#                                                                 #\n" .
"###################################################################\n";
        fwrite($this->fp, $header);
    }
    
    protected function createFile($dir) {
        $full_file = $dir . '/' . $this->generate_filename;
        if (!($this->fp = @fopen($full_file, 'w+'))) {
            throw new Exception("Cannot open file (writing permission) '" . $full_file ."'");
        }
        $this->setHeader();
    }
    
    protected function writeObject($object) {
        $object_file = "\n";
        $object_file .= 'define ' . $this->object_name . " {\n";
                
        foreach ($this->attributes_write as &$attr) {
            if (isset($object[$attr]) && !is_null($object[$attr]) && $object[$attr] != '') {
                $object_file .= sprintf("    %-30s %s\n", $attr, $object[$attr]);
            }
        }
        
        foreach ($this->attributes_default as &$attr) {
            if (isset($object[$attr]) && !is_null($object[$attr]) && $object[$attr] != 2) {
                $object_file .= sprintf("    %-30s %s\n", $attr, $object[$attr]);
            }
        }
        
        foreach ($this->attributes_array as &$attr) {
            if (isset($object[$attr]) && !is_null($object[$attr])) {
                $str = '';
                $str_append = '';
                foreach ($object[$attr] as &$value) {
                    if (!is_null($value)) {
                        $str .= $str_append . $value;
                        $str_append = ',';
                    }
                }
                
                if ($str != '') {
                    $object_file .= sprintf("    %-30s %s\n", $attr, $str);
                }
            }
        }
        
        foreach ($this->attributes_hash as &$attr) {
            if (!isset($object[$attr])) {
                continue;
            }
            foreach ($object[$attr] as $key => &$value) {
                 $object_file .= sprintf("    %-30s %s\n", $key, $value);
            }
        }
        
        $object_file .= "}\n";
        fwrite($this->fp, $object_file);
    }
    
    protected function generateObjectInFile($object, $id) {
        if (is_null($this->fp)) {
            $this->createFile($this->backend_instance->getPath());
        }
        $this->writeObject($object);
        $this->exported[$id] = 1;
    }
    
    private function writeNoObject($object) {        
        foreach ($this->attributes_array as &$attr) {
            if (isset($object[$attr]) && !is_null($object[$attr]) && is_array($object[$attr])) {
                foreach ($object[$attr] as $v) {
                    fwrite($this->fp, $attr . "=" . $v . "\n");
                }
            }
        }
        
        foreach ($this->attributes_hash as &$attr) {
            if (!isset($object[$attr])) {
                continue;
            }
            foreach ($object[$attr] as $key => &$value) {
                fwrite($this->fp, $key . "=" . $value . "\n");
            }
        }
        
        foreach ($this->attributes_write as &$attr) {
            if (isset($object[$attr]) && !is_null($object[$attr]) && $object[$attr] != '') {
                fwrite($this->fp, $attr . "=" . $object[$attr] . "\n");
            }
        }
        
        foreach ($this->attributes_default as &$attr) {
            if (isset($object[$attr]) && !is_null($object[$attr]) && $object[$attr] != 2) {
                fwrite($this->fp, $attr . "=" . $object[$attr] . "\n");
            }
        }
    }
    
    protected function generateFile($object) {
        if (is_null($this->fp)) {
            $this->createFile($this->backend_instance->getPath());
        }
        
        $this->writeNoObject($object);
    }
    
    public function checkGenerate($id) {
        if (isset($this->exported[$id])) {
            return 1;
        }
        return 0;
    }

    public function getExported() {
        if (isset($this->exported)) {
            return $this->exported;
        }
        return array();
    }
}

?>
