version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  # Maintain dependencies for Javascript
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"
    commit-message:
      prefix: "npm prod."
    open-pull-requests-limit: 10
    versioning-strategy: increase-if-necessary
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch", "version-update:semver-minor", "version-update:semver-major"]


  # Maintain dependencies for PHP
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"
    commit-message:
      prefix: "composer prod."
    open-pull-requests-limit: 10
    versioning-strategy: increase-if-necessary
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch", "version-update:semver-minor", "version-update:semver-major"]

  # Maintain dependencies for Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"
    commit-message:
      prefix: "pip prod."
    open-pull-requests-limit: 10

  # Maintain dependencies for Java
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"
    commit-message:
      prefix: "maven prod."
    open-pull-requests-limit: 10
