jms_serializer:
    metadata:
        directories:
            centreon:
                namespace_prefix: "Centreon\\Domain"
                path: '%kernel.project_dir%/config/packages/serializer/Centreon'
            application:
                namespace_prefix: "Centreon\\Application"
                path: '%kernel.project_dir%/config/packages/serializer/Application'
            infrastructure:
                namespace_prefix: "Centreon\\Infrastructure"
                path: '%kernel.project_dir%/config/packages/serializer/Infrastructure'
            core:
                namespace_prefix: "Core\\"
                path: '%kernel.project_dir%/config/packages/serializer/Core'
parameters:
    api.header: "Api-Version"
    api.version.latest: "22.10"
    debug_log_file: '%log_path%/centreon-web.log'
    env(DEBUG_LEVEL): !php/const Monolog\Logger::NOTICE
    curl.timeout: 60
    debug_level: "%env(int:DEBUG_LEVEL)%"
    env(DEBUG_CONTACT): null

services:
    _defaults:
        public: false
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, controller...

    Centreon\:
        resource: '../../src/Centreon/*'
        exclude: '../../src/Centreon/Tests'

    Core\:
        resource: '../../src/Core/*'

    Centreon\Infrastructure\DatabaseConnection:
        class: Centreon\Infrastructure\DatabaseConnection
        arguments:
            $host: '%database_host%'
            $port: '%database_port%'
            $basename: '%database_db%'
            $login: '%database_user%'
            $password: '%database_password%'
        calls:
            - method: setCentreonDbName
              arguments: ['%database_db%']
            - method: setStorageDbName
              arguments: ['%database_dbstg%']

    jms_serializer.object_constructor:
        class: Centreon\Infrastructure\Serializer\ObjectConstructor
        public: false

    json_presenter:
        class: Core\Infrastructure\Common\Presenter\JsonPresenter
        public: false

    Core\Infrastructure\Common\Presenter\PresenterFormatterInterface:
        class: Core\Infrastructure\Common\Presenter\JsonPresenter
        public: false

    # Encryption
    Security\Interfaces\EncryptionInterface:
        class: Security\Encryption
        calls:
            - method: setFirstKey
              arguments: ['%env(APP_SECRET)%']

    # JSON Validator
    Centreon\Domain\Service\JsonValidator\Interfaces\JsonValidatorInterface:
        class: Centreon\Domain\Service\JsonValidator\Validator
        arguments: ['%env(_CENTREON_PATH_)%config/json_validator']

    Centreon\Domain\Service\JsonValidator\Interfaces\ValidatorCacheInterface:
        class: Centreon\Domain\Service\JsonValidator\ValidatorCache
        arguments: ["%kernel.cache_dir%/JsonValidatorCache", '%kernel.debug%']

    # Contact
    Centreon\Domain\Contact\Interfaces\ContactInterface:
        class: Centreon\Domain\Contact\Contact
        public: true

    Centreon\Domain\Contact\Interfaces\ContactServiceInterface:
        class: Centreon\Domain\Contact\ContactService
        public: true

    Centreon\Domain\Contact\Interfaces\ContactRepositoryInterface:
        class: Centreon\Infrastructure\Contact\ContactRepositoryRDB

    contact.provider:
        class: Centreon\Domain\Contact\ContactProvider
        public: true

    presenter.download.csv:
        class: Core\Infrastructure\Common\Presenter\DownloadPresenter
        arguments: ['@Core\Infrastructure\Common\Presenter\CsvPresenter']

    Core\Application\RealTime\UseCase\FindPerformanceMetrics\FindPerformanceMetricPresenterInterface:
        class: Core\Infrastructure\RealTime\Api\DownloadPerformanceMetrics\DownloadPerformanceMetricsPresenter
        arguments: ['@presenter.download.csv']

    # Authentication
    Core\Security\AccessGroup\Application\Repository\ReadAccessGroupRepositoryInterface:
        class: Core\Security\AccessGroup\Infrastructure\Repository\DbReadAccessGroupRepository

    Centreon\Domain\RequestParameters\Interfaces\RequestParametersInterface:
        class: Centreon\Domain\RequestParameters\RequestParameters

    Security\Domain\Authentication\Interfaces\AuthenticationTokenServiceInterface:
        class: Security\Domain\Authentication\AuthenticationTokenService

    # Icon configuration
    Centreon\Domain\Configuration\Icon\Interfaces\IconServiceInterface:
        class: Centreon\Domain\Configuration\Icon\IconService

    Centreon\Domain\Configuration\Icon\Interfaces\IconRepositoryInterface:
        class: Centreon\Infrastructure\Icon\IconRepositoryRDB
        calls:
            - method: setSqlRequestTranslator
              arguments: ['@sqlRequestTranslator']

    # Poller configuration
    Centreon\Domain\MonitoringServer\Interfaces\MonitoringServerServiceInterface:
        class: Centreon\Domain\MonitoringServer\MonitoringServerService

    Centreon\Domain\MonitoringServer\Interfaces\MonitoringServerRepositoryInterface:
        class: Centreon\Infrastructure\MonitoringServer\MonitoringServerRepositoryRDB
        calls:
            - method: setSqlRequestTranslator
              arguments: ['@sqlRequestTranslator']

    Centreon\Domain\MonitoringServer\Interfaces\MonitoringServerConfigurationRepositoryInterface:
        class: Centreon\Infrastructure\MonitoringServer\Repository\MonitoringServerConfigurationRepositoryApi
        public: true
        calls:
        - method: setTimeout
          arguments: ['%curl.timeout%']

    # Platform topology register server
    Centreon\Domain\PlatformTopology\Interfaces\PlatformTopologyServiceInterface:
        class: Centreon\Domain\PlatformTopology\PlatformTopologyService

    Centreon\Domain\PlatformTopology\Interfaces\PlatformTopologyRepositoryInterface:
        class: Centreon\Infrastructure\PlatformTopology\Repository\PlatformTopologyRepositoryRDB

    Centreon\Domain\PlatformTopology\Interfaces\PlatformTopologyRegisterRepositoryInterface:
        class: Centreon\Infrastructure\PlatformTopology\Repository\PlatformTopologyRegisterRepositoryAPI

    # Real time monitoring
    sqlRequestTranslator:
        class: Centreon\Infrastructure\RequestParameters\SqlRequestParametersTranslator

    Centreon\Domain\Monitoring\Interfaces\MonitoringServiceInterface:
        class: Centreon\Domain\Monitoring\MonitoringService
        public: true

    Centreon\Domain\Monitoring\Interfaces\MonitoringRepositoryInterface:
        class: Centreon\Infrastructure\Monitoring\MonitoringRepositoryRDB
        calls:
            - method: setSqlRequestTranslator
              arguments: ['@sqlRequestTranslator']

    Centreon\Domain\Monitoring\HostGroup\Interfaces\HostGroupServiceInterface:
        class: Centreon\Domain\Monitoring\HostGroup\HostGroupService

    Centreon\Domain\Monitoring\HostGroup\Interfaces\HostGroupRepositoryInterface:
        class: Centreon\Infrastructure\Monitoring\HostGroup\HostGroupRepositoryRDB

    Centreon\Domain\Monitoring\ServiceGroup\Interfaces\ServiceGroupServiceInterface:
        class: Centreon\Domain\Monitoring\ServiceGroup\ServiceGroupService

    Centreon\Domain\Monitoring\ServiceGroup\Interfaces\ServiceGroupRepositoryInterface:
        class: Centreon\Infrastructure\Monitoring\ServiceGroup\ServiceGroupRepositoryRDB

    # Downtime
    Centreon\Domain\Downtime\Interfaces\DowntimeServiceInterface:
        class: Centreon\Domain\Downtime\DowntimeService

    # Engine
    Centreon\Domain\Engine\Interfaces\EngineRepositoryInterface:
        class: Centreon\Infrastructure\Engine\EngineRepositoryFile
        arguments: ['%centreon_var_lib%/centcore']

    Centreon\Domain\Engine\Interfaces\EngineServiceInterface:
        class: Centreon\Domain\Engine\EngineService

    Core\Domain\Engine\Model\EngineCommandGenerator:
        public: true
        arguments:
            - !tagged_iterator 'engine.command.generator'

    # API Acknowledgement
    Centreon\Domain\Acknowledgement\Interfaces\AcknowledgementRepositoryInterface:
        class: Centreon\Infrastructure\Acknowledgement\AcknowledgementRepositoryRDB

    Centreon\Domain\Acknowledgement\Interfaces\AcknowledgementServiceInterface:
        class: Centreon\Domain\Acknowledgement\AcknowledgementService

    # Metric
    Centreon\Domain\Monitoring\Metric\Interfaces\MetricServiceInterface:
        class: Centreon\Domain\Monitoring\Metric\MetricService

    # Proxy configuration
    Centreon\Domain\Proxy\Interfaces\ProxyServiceInterface:
        class: Centreon\Domain\Proxy\ProxyService

    Centreon\Domain\Proxy\Interfaces\ProxyRepositoryInterface:
        class: Centreon\Infrastructure\Proxy\ProxyRepositoryRDB

    Centreon\Domain\Gorgone\Interfaces\GorgoneServiceInterface:
        class: Centreon\Domain\Gorgone\GorgoneService
        public: true

    # Information data used in the configuration
    Centreon\Domain\PlatformInformation\Interfaces\PlatformInformationServiceInterface:
        class: Centreon\Domain\PlatformInformation\PlatformInformationService

    Centreon\Domain\PlatformInformation\Interfaces\PlatformInformationRepositoryInterface:
        class: Centreon\Infrastructure\PlatformInformation\Repository\PlatformInformationRepositoryRDB
        calls:
            - [setEncryptionFirstKey, ['%env(APP_SECRET)%']]

    Centreon\Domain\PlatformInformation\Interfaces\PlatformInformationReadRepositoryInterface:
        class: Centreon\Infrastructure\PlatformInformation\Repository\PlatformInformationRepositoryRDB
        calls:
            - [setEncryptionFirstKey, ['%env(APP_SECRET)%']]

    Centreon\Domain\PlatformInformation\UseCase\V20\UpdatePartiallyPlatformInformation:
        class: Centreon\Domain\PlatformInformation\UseCase\V20\UpdatePartiallyPlatformInformation
        calls:
            - [setEncryptionFirstKey, ['%env(APP_SECRET)%']]

    Core\Infrastructure\Platform\Repository\FileReadPlatformRepository:
        class: Core\Infrastructure\Platform\Repository\FileReadPlatformRepository
        arguments: ['%centreon_etc_path%', '%centreon_install_path%']

    Core\Platform\Application\Validator\RequirementValidatorsInterface:
        class: Core\Platform\Infrastructure\Validator\RequirementValidators
        arguments:
            $requirementValidators: !tagged_iterator 'platform.requirement.validators'

    Core\Platform\Infrastructure\Validator\RequirementValidators\DatabaseRequirementValidator:
        arguments:
            $dbRequirementValidators: !tagged_iterator 'platform.requirement.database.validators'

    Core\Platform\Infrastructure\Validator\RequirementValidators\PhpRequirementValidator:
        arguments:
            $requiredPhpVersion: '%required_php_version%'

    Core\Platform\Infrastructure\Validator\RequirementValidators\DatabaseRequirementValidators\MariaDbRequirementValidator:
        arguments:
            $requiredMariaDbMinVersion: '%required_mariadb_min_version%'

    Core\Platform\Application\Repository\ReadVersionRepositoryInterface:
        class: Core\Platform\Infrastructure\Repository\DbReadVersionRepository
        public: true

    Core\Platform\Application\Repository\ReadUpdateRepositoryInterface:
        class: Core\Platform\Infrastructure\Repository\FsReadUpdateRepository
        arguments:
            $installDir: '%centreon_install_path%'
        public: true

    Core\Platform\Application\Repository\UpdateLockerRepositoryInterface:
        class: Core\Platform\Infrastructure\Repository\SymfonyUpdateLockerRepository
        public: true

    Core\Platform\Application\Repository\WriteUpdateRepositoryInterface:
        class: Core\Platform\Infrastructure\Repository\DbWriteUpdateRepository
        arguments: ['%centreon_var_lib%', '%centreon_install_path%']
        public: true

    # Monitoring resources
    _instanceof:
        Core\Infrastructure\RealTime\Hypermedia\HypermediaProviderInterface:
            tags: ['realtime.hypermedia']
        Core\Domain\RealTime\ResourceTypeInterface:
            tags: ['monitoring.resource.type']
        Core\Resources\Infrastructure\Repository\ResourceACLProviders\ResourceACLProviderInterface:
            tags: ['monitoring.resource.acl']
        Core\Security\ProviderConfiguration\Application\Repository\ReadProviderConfigurationsRepositoryInterface:
            tags: ['authentication.provider.repositories']
        Core\Security\ProviderConfiguration\Application\UseCase\FindProviderConfigurations\ProviderResponse\ProviderResponseInterface:
            tags: ['authentication.provider.responses']
        Core\Security\ProviderConfiguration\Infrastructure\Api\FindProviderConfigurations\ProviderPresenter\ProviderPresenterInterface:
            tags: ['authentication.provider.presenters']
        Core\Platform\Application\Validator\RequirementValidatorInterface:
            tags: ['platform.requirement.validators']
        Core\Platform\Infrastructure\Validator\RequirementValidators\DatabaseRequirementValidatorInterface:
            tags: ['platform.requirement.database.validators']

    Core\Security\ProviderConfiguration\Application\UseCase\FindProviderConfigurations\FindProviderConfigurations:
        arguments:
          - !tagged_iterator 'authentication.provider.responses'

    Core\Security\ProviderConfiguration\Infrastructure\Api\FindProviderConfigurations\FindProviderConfigurationsPresenter:
        arguments: [!tagged_iterator 'authentication.provider.presenters']

    Core\Infrastructure\RealTime\Hypermedia\HypermediaCreator:
        class: Core\Infrastructure\RealTime\Hypermedia\HypermediaCreator
        calls:
            - method: setHypermediaProviders
              arguments: [!tagged_iterator 'realtime.hypermedia']

    # Filters
    Centreon\Domain\Filter\Interfaces\FilterServiceInterface:
        class: Centreon\Domain\Filter\FilterService

    Centreon\Domain\Filter\Interfaces\FilterRepositoryInterface:
        class: Centreon\Infrastructure\Filter\FilterRepositoryRDB
        calls:
            - method: setSqlRequestTranslator
              arguments: ['@sqlRequestTranslator']

    # Monitoring Timeline
    Centreon\Domain\Monitoring\Timeline\Interfaces\TimelineServiceInterface:
        class: Centreon\Domain\Monitoring\Timeline\TimelineService

    Centreon\Domain\Monitoring\Timeline\Interfaces\TimelineRepositoryInterface:
        class: Centreon\Infrastructure\Monitoring\Timeline\TimelineRepositoryRDB
        calls:
            - method: setSqlRequestTranslator
              arguments: ['@sqlRequestTranslator']

    # Host configuration
    Centreon\Domain\HostConfiguration\Interfaces\HostConfigurationRepositoryInterface:
        class: Centreon\Infrastructure\HostConfiguration\Repository\HostConfigurationRepositoryRDB

    Centreon\Domain\HostConfiguration\Interfaces\HostCategory\HostCategoryReadRepositoryInterface:
        class: Centreon\Infrastructure\HostConfiguration\Repository\HostCategoryRepositoryRDB

    Centreon\Domain\HostConfiguration\Interfaces\HostConfigurationServiceInterface:
        class: Centreon\Domain\HostConfiguration\HostConfigurationService
        public: true

    # Host category
    Centreon\Domain\HostConfiguration\Interfaces\HostCategory\HostCategoryServiceInterface:
        class: Centreon\Domain\HostConfiguration\HostCategoryService

    Centreon\Domain\HostConfiguration\Interfaces\HostSeverity\HostSeverityServiceInterface:
        class: Centreon\Domain\HostConfiguration\HostSeverityService

    Centreon\Domain\HostConfiguration\Interfaces\HostSeverity\HostSeverityReadRepositoryInterface:
        class: Centreon\Infrastructure\HostConfiguration\Repository\HostSeverityRepositoryRDB

    Centreon\Domain\HostConfiguration\UseCase\V2110\HostSeverity\FindHostSeverities:
        class: Centreon\Domain\HostConfiguration\UseCase\V2110\HostSeverity\FindHostSeverities
        calls:
            - method: setMediaPath
              arguments: ["%media_path%"]

    # Host group configuration
    Centreon\Domain\HostConfiguration\Interfaces\HostGroup\HostGroupReadRepositoryInterface:
        class: Centreon\Infrastructure\HostConfiguration\Repository\HostGroupRepositoryRDB

    Centreon\Domain\HostConfiguration\UseCase\V2110\HostGroup\FindHostGroups:
        class: Centreon\Domain\HostConfiguration\UseCase\V2110\HostGroup\FindHostGroups
        calls:
            - method: setMediaPath
              arguments: ["%media_path%"]

    # Service configuration
    Centreon\Domain\ServiceConfiguration\Interfaces\ServiceConfigurationServiceInterface:
        class: Centreon\Domain\ServiceConfiguration\ServiceConfigurationService

    Centreon\Domain\ServiceConfiguration\Interfaces\ServiceConfigurationRepositoryInterface:
        class: Centreon\Infrastructure\ServiceConfiguration\ServiceConfigurationRepositoryRDB

    # Action log
    Centreon\Domain\ActionLog\Interfaces\ActionLogRepositoryInterface:
        class: Centreon\Infrastructure\ActionLog\ActionLogRepositoryRDB

    Centreon\Domain\ActionLog\Interfaces\ActionLogServiceInterface:
        class: Centreon\Domain\ActionLog\ActionLogService

    # Broker
    Centreon\Domain\Broker\Interfaces\BrokerRepositoryInterface:
        class: Centreon\Infrastructure\Broker\BrokerRepositoryRDB

    # Remote Server
    Centreon\Domain\RemoteServer\Interfaces\RemoteServerServiceInterface:
        class: Centreon\Domain\RemoteServer\RemoteServerService

    Centreon\Domain\RemoteServer\Interfaces\RemoteServerLocalConfigurationRepositoryInterface:
        class: Centreon\Infrastructure\RemoteServer\RemoteServerRepositoryFile
        calls:
            - [setCentreonConfFilePath, ['%centreon_etc_path%/conf.pm']]

    Centreon\Domain\RemoteServer\Interfaces\RemoteServerRepositoryInterface:
        class: Centreon\Infrastructure\RemoteServer\RemoteServerRepositoryRDB

    # Menu
    Centreon\Domain\Menu\Interfaces\MenuRepositoryInterface:
        class: Centreon\Infrastructure\Menu\MenuRepositoryRDB

    Core\Security\Authentication\Application\UseCase\LoginSession\LoginSession:
        arguments: [ "%redirect_default_page%" ]
        public: true

    Core\Security\Authentication\Application\UseCase\LoginOpenIdSession\LoginOpenIdSession:
        arguments: [ "%redirect_default_page%" ]
        public: true

    Security\Domain\Authentication\Interfaces\OpenIdProviderInterface:
        class: Core\Security\Authentication\Domain\Provider\OpenIdProvider
        tags: ['authentication.providers']

    Security\Domain\Authentication\Interfaces\WebSSOProviderInterface:
        class: Core\Security\Authentication\Domain\Provider\WebSSOProvider
        tags: ['authentication.providers']

    Centreon\Domain\Authentication\UseCase\AuthenticateApi:
        public: true

    # Log configuration
    monolog.error.formater:
        class: Monolog\Formatter\LineFormatter
        arguments: [ "%%level_name%%: %%message%% %%context%%\n" ]

    monolog.debug.formater:
        class: Monolog\Formatter\LineFormatter
        arguments: [ "[%%datetime%%] [%%level_name%%] %%message%% %%context%%\n", !php/const DateTimeInterface::ISO8601, false, true ]

    monolog.debug.handler:
        class: Centreon\Domain\Log\DebugFileHandler
        arguments: [ '@monolog.debug.formater', '%debug_log_file%', '%env(bool:APP_DEBUG)%', 664, '%debug_level%' ]

    Centreon\Domain\Log\ContactForDebug:
        class: Centreon\Domain\Log\ContactForDebug
        arguments: ['%env(DEBUG_CONTACT)%']

    Centreon\Domain\Log\LegacyLogger:
        public: true

    # Session
    Core\Application\Common\Session\Repository\ReadSessionRepositoryInterface:
        class: Core\Infrastructure\Common\Repository\MultiReadSessionRepository
        public: true