nelmio_cors:
    defaults:
        allow_credentials: false
        origin_regex: true
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'Origin', 'Accept', 'X-AUTH-TOKEN']
        expose_headers: ['Link']
        hosts: ['*']
        max_age: 3600
