centreon_security_create_hashicorp_vault_configuration:
    methods: POST
    path: /administration/vaults/hashicorp
    controller: 'Core\Security\Vault\Infrastructure\Api\CreateHashiCorpVaultConfiguration\CreateHashiCorpVaultConfigurationController'
    condition: "request.attributes.get('version') >= 22.10"
