<?php
/*
 * Copyright 2015 Centreon (http://www.centreon.com/)
 * 
 * Centreon is a full-fledged industry-strength solution that meets 
 * the needs in IT infrastructure and application monitoring for 
 * service performance.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *    http://www.apache.org/licenses/LICENSE-2.0  
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 * For more information : contact@centreon.com
 * 
 */

$help = array();

/**
 * Centcore Settings
 */
$help['tip_enable_perfdata_sync'] = dgettext('help', 'Enable Perfdata synchronisation between poller and Central Server operated by Centore');
$help['tip_enable_logs_sync'] = dgettext('help', 'Enable Monitoring Engine Logs synchronisation between poller and Central Server operated by Centore');
$help['tip_centcore_cmd_timeout'] = dgettext('help', "Timeout value in seconds. Used for freeing Centcore when it's stuck because of blocking pipe files or SSH connections.");
$help['tip_enable_broker_stats'] = dgettext('help', "Enable Centreon Broker statistics collection into the central server in order to reduce the network load generated by Centcore. Be carefull : broker statistics will not be available into Home > Broker statistics.");