configuration_access_group_find_all:
  methods: GET
  path: /configuration/access-groups
  controller: 'Core\Security\Infrastructure\Api\FindUserAccessGroups\FindUserAccessGroupsController'
  condition: "request.attributes.get('version') >= 22.04"