configuration_access_group_find_all:
  methods: GET
  path: /configuration/access-groups
  controller: 'Core\Security\AccessGroup\Infrastructure\Api\FindLocalUserAccessGroups\FindLocalUserAccessGroupsController'
  condition: "request.attributes.get('version') >= 22.04"