configuration_contact_template_find_all:
  methods: GET
  path: /configuration/contact/template
  controller: 'Core\Contact\Infrastructure\Api\FindContactTemplates\FindContactTemplatesController'
  condition: "request.attributes.get('version') >= 22.04"