#!/usr/bin/env perl

use warnings;
use centreon::script::centstorage_purge;

centreon::script::centstorage_purge->new()->run();

__END__

=head1 NAME

centstorage_purge - a script to keep the centstorage database clean.

=head1 SYNOPSIS

logAnalyser [options]

=head1 OPTIONS

=over 8

=item B<--config>

Specify the path to the main configuration file (default: /etc/centreon/centreon-config.pm).

=item B<--logfile>

Write log messages into this file instead of the standard output.

=item B<--help>

Print a brief help message and exits.

=back

=head1 DESCRIPTION

B<centstorage_purge> will delete records from the database (databin,
log and ?? tables) depending on the retention policy defined in
Centreon.

=cut
