<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Service</name>
   <tag></tag>
   <elementGuidId>cc8e9dc3-a1ff-4f4a-b724-9c9cec43cd3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@name = 'metric_sel[0]' and (text() = '
	
	Cpu
	Load
	Memory
	Ping
	proc-broker-rrd
	proc-broker-sql
	proc-centcore
	proc-centengine
	proc-crond
	proc-httpd
	proc-ntpd
	proc-sshd
	Swap
' or . = '
	
	Cpu
	Load
	Memory
	Ping
	proc-broker-rrd
	proc-broker-sql
	proc-centcore
	proc-centengine
	proc-crond
	proc-httpd
	proc-ntpd
	proc-sshd
	Swap
')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>metric_sel[0]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>_hs_swapOptions(this.form, 'metric_sel', 0);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Form&quot;)/table[@class=&quot;ListTable&quot;]/tbody[1]/tr[@class=&quot;list_two&quot;]/td[2]/select[1]</value>
   </webElementProperties>
</WebElementEntity>
