export const labelRequired = 'Required';
export const labelLoginSucceeded = 'Login succeeded';
export const labelAlias = 'Alias';
export const labelPassword = 'Password';
export const labelLogin = 'Login';
export const labelCentreonLogo = 'Centreon Logo';
export const labelConnect = 'Connect';
export const labelDisplayThePassword = 'Display the password';
export const labelHideThePassword = 'Hide the password';
