<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>add_sg</name>
   <tag></tag>
   <elementGuidId>d4d5d752-3ad9-4f00-8400-2e4b3df37db6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;tab3&quot;)/table[@class=&quot;formTable table&quot;]/tbody[1]/tr[@class=&quot;list_one&quot;]/td[@class=&quot;FormRowValue&quot;]/table[1]/tbody[1]/tr[1]/td[2]/input[@class=&quot;btc bt_success&quot;][count(. | //input[@name = 'add' and @value = 'Add' and @class = 'btc bt_success' and @onclick = concat('QFAMS.moveSelection(' , &quot;'&quot; , 'acl_sg' , &quot;'&quot; , ', this.form.elements[' , &quot;'&quot; , 'acl_sg-f[]' , &quot;'&quot; , '], this.form.elements[' , &quot;'&quot; , 'acl_sg-t[]' , &quot;'&quot; , '], this.form.elements[' , &quot;'&quot; , 'acl_sg[]' , &quot;'&quot; , '], ' , &quot;'&quot; , 'add' , &quot;'&quot; , ', ' , &quot;'&quot; , 'asc' , &quot;'&quot; , '); return false;') and @type = 'button']) = count(//input[@name = 'add' and @value = 'Add' and @class = 'btc bt_success' and @onclick = concat('QFAMS.moveSelection(' , &quot;'&quot; , 'acl_sg' , &quot;'&quot; , ', this.form.elements[' , &quot;'&quot; , 'acl_sg-f[]' , &quot;'&quot; , '], this.form.elements[' , &quot;'&quot; , 'acl_sg-t[]' , &quot;'&quot; , '], this.form.elements[' , &quot;'&quot; , 'acl_sg[]' , &quot;'&quot; , '], ' , &quot;'&quot; , 'add' , &quot;'&quot; , ', ' , &quot;'&quot; , 'asc' , &quot;'&quot; , '); return false;') and @type = 'button'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>add</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Add</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btc bt_success</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>QFAMS.moveSelection('acl_sg', this.form.elements['acl_sg-f[]'], this.form.elements['acl_sg-t[]'], this.form.elements['acl_sg[]'], 'add', 'asc'); return false;</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab3&quot;)/table[@class=&quot;formTable table&quot;]/tbody[1]/tr[@class=&quot;list_one&quot;]/td[@class=&quot;FormRowValue&quot;]/table[1]/tbody[1]/tr[1]/td[2]/input[@class=&quot;btc bt_success&quot;]</value>
   </webElementProperties>
</WebElementEntity>
