<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_hg</name>
   <tag></tag>
   <elementGuidId>bd67ff24-5a16-42ff-822d-34a26ca48045</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;acl_hostgroup-f&quot;)/option[count(. | //option[(text() = 'Katalon_user_group' or . = 'Katalon_user_group')]) = count(//option[(text() = 'Katalon_user_group' or . = 'Katalon_user_group')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>option</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Katalon_user_group</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acl_hostgroup-f&quot;)/option</value>
   </webElementProperties>
</WebElementEntity>
