<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_exclude_host</name>
   <tag></tag>
   <elementGuidId>bc98b2dc-c793-4550-8f9c-02bbc2775b64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;acl_hostexclude-f&quot;)/option[count(. | //option[(text() = 'pouic_1' or . = 'pouic_1')]) = count(//option[(text() = 'pouic_1' or . = 'pouic_1')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>option</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>pouic_1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acl_hostexclude-f&quot;)/option</value>
   </webElementProperties>
</WebElementEntity>
