<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_metaService</name>
   <tag></tag>
   <elementGuidId>60709981-4d15-460e-b3a2-7fd3c730a9b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;acl_meta-f&quot;)/option[count(. | //option[(text() = 'Ping-RTA-Average' or . = 'Ping-RTA-Average')]) = count(//option[(text() = 'Ping-RTA-Average' or . = 'Ping-RTA-Average')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>option</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ping-RTA-Average</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acl_meta-f&quot;)/option</value>
   </webElementProperties>
</WebElementEntity>
