<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_hosts</name>
   <tag></tag>
   <elementGuidId>13d37cb4-052f-490b-95fd-6a99ee45aede</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//option[(text() = 'pouic' or . = 'pouic')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>option</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>pouic</value>
   </webElementProperties>
</WebElementEntity>
