_("Home")
_("Monitoring")
_("Reporting")
_("Views")
_("ID Cards")
_("Administration")
_("Configuration")
_("Nagios Statistics")
_("Hosts")
_("Services")
_("Users")
_("Nagios")
_("Commands")
_("Centreon")
_("Notifications")
_("Hosts Group")
_("Templates")
_("Services Groups")
_("SNMP Traps")
_("Manufacturer")
_("MIBs")
_("Categories")
_("Contacts / Users")
_("Contacts Groups")
_("Time Periods")
_("Commands")
_("Checks")
_("Miscellaneous")
_("Plugins")
_("Escalations")
_("Dependencies")
_("Optimize")
_("nagios.cfg")
_("cgi")
_("resources")
_("Load")
_("Generate")
_("ndomod.cfg")
_("ndo2db.cfg")
_("Pollers")
_("ACL")
_("Databases")
_("Sessions")
_("Server Status")
_("Languages")
_("Modules")
_("My Account")
_("CentStorage")
_("Upgrade")
_("CSS")
_("Debug")
_("RRDTool")
_("SNMP")
_("LDAP")
_("Colors")
_("Check Version")
_("Pre-Update")
_("Manage")
_("Bugs Tracker")
_("Web Sites")
_("Wiki")
_("Forum")
_("Donate")
_("Support")
_("Inventory")
_("Servers")
_("Graphs")
_("Centreon Status Map")
_("Localisations")
_("Curves")
_("Dashboard")
_("Event Logs")
_("Services Details")
_("Details")
_("Services Problems")
_("All Services")
_("Grids")
_("Resume")
_("Summary")
_("Scheduling Queue")
_("Hosts Problems")
_("Downtime")
_("Comments")
