<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_editView</name>
   <tag></tag>
   <elementGuidId>9a5b9eb0-3a34-4ab8-87b5-e1a057ce1669</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;globalView&quot;)/div[@class=&quot;toggleEdit&quot;]/a[1]/img[@class=&quot;ico-14&quot;][count(. | //img[@class = 'ico-14']) = count(//img[@class = 'ico-14'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ico-14</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;globalView&quot;)/div[@class=&quot;toggleEdit&quot;]/a[1]/img[@class=&quot;ico-14&quot;]</value>
   </webElementProperties>
</WebElementEntity>
