#! /usr/bin/perl -w
################################################################################
# Copyright 2005-2009 MERETHIS
# Centreon is developped by : Julien Mathis and Romain Le Merlus under
# GPL Licence 2.0.
# 
# This program is free software; you can redistribute it and/or modify it under 
# the terms of the GNU General Public License as published by the Free Software 
# Foundation ; either version 2 of the License.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
# PARTICULAR PURPOSE. See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along with 
# this program; if not, see <http://www.gnu.org/licenses>.
# 
# Linking this program statically or dynamically with other modules is making a 
# combined work based on this program. Thus, the terms and conditions of the GNU 
# General Public License cover the whole combination.
# 
# As a special exception, the copyright holders of this program give MERETHIS 
# permission to link this program with independent modules to produce an executable, 
# regardless of the license terms of these independent modules, and to copy and 
# distribute the resulting executable under terms of MERETHIS choice, provided that 
# MERETHIS also meet, for each linked independent module, the terms  and conditions 
# of the license of that module. An independent module is a module which is not 
# derived from this program. If you modify this program, you may extend this 
# exception to your version of the program, but you are not obliged to do so. If you
# do not wish to do so, delete this exception statement from your version.
# 
# For more information : contact@centreon.com
# 
# SVN : $URL$
# SVN : $Id$
#
####################################################################################

use strict;
use warnings;
use DBI;
use File::stat;
use Getopt::Long;
use POSIX;

use vars qw($mysql_user $mysql_passwd $mysql_host $mysql_database_oreon $mysql_database_ods $opt_h $opt_a $data);

my $rsyncPath = "rsync";

require "@CENTREON_ETC@/conf.pm";

## Init Date
my ($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = gmtime(time);

# Init MySQL Connexion
my $dbhoreon = DBI->connect("DBI:mysql:database=".$mysql_database_oreon.";host=".$mysql_host, $mysql_user, $mysql_passwd, {'RaiseError' => 1});

# SnmpTT configurations files
my $sth2 = $dbhoreon->prepare("SELECT `id`, `ns_ip_address` FROM `nagios_server` WHERE `ns_activate` = '1' AND `localhost` = '0'");
if (!$sth2->execute) {
    die "Error:" . $sth2->errstr . "\n";
} else { 
	while (my $ns_server = $sth2->fetchrow_hashref()) {
		my $sth3 = $dbhoreon->prepare("SELECT `log_archive_path` FROM `cfg_nagios` WHERE `ns_server_id` = '".$ns_server->{'id'}."' AND `nagios_activate` = '1'");
		if ($sth3->execute()) {
			my $data = $sth3->fetchrow_hashref();
			# Archive Sync
			`$rsyncPath -c $ns_server->{'ns_ip_address'}:$data->{'log_archive_path'}/* @VARLIB_CENTREON@@/log/$ns_server->{'id'}/archives/`;
			unset($data);
		} else {
			print "Can't get archive path for service ".$ns_server->{'id'}." (".$ns_server->{'ns_address_ip'}.") -> ".$sth3->$sth2->errstr;
		}		
	}
}

exit();
