#!/usr/bin/env perl
################################################################################
# Copyright 2005-2015 Centreon
# Centreon is developped by : Julien Mathis and Romain Le Merlus under
# GPL Licence 2.0.
# 
# This program is free software; you can redistribute it and/or modify it under 
# the terms of the GNU General Public License as published by the Free Software 
# Foundation ; either version 2 of the License.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
# PARTICULAR PURPOSE. See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along with 
# this program; if not, see <http://www.gnu.org/licenses>.
# 
# Linking this program statically or dynamically with other modules is making a 
# combined work based on this program. Thus, the terms and conditions of the GNU 
# General Public License cover the whole combination.
# 
# As a special exception, the copyright holders of this program give Centreon 
# permission to link this program with independent modules to produce an executable, 
# regardless of the license terms of these independent modules, and to copy and 
# distribute the resulting executable under terms of Centreon choice, provided that 
# Centreon also meet, for each linked independent module, the terms  and conditions 
# of the license of that module. An independent module is a module which is not 
# derived from this program. If you modify this program, you may extend this 
# exception to your version of the program, but you are not obliged to do so. If you
# do not wish to do so, delete this exception statement from your version.
# 
####################################################################################

use warnings;
use centreon::script::dashboardBuilder;

centreon::script::dashboardBuilder->new()->run();

__END__

=head1 NAME

dashboardBuilder - script to update dashboards

=head1 SYNOPSIS

dashboardBuilder [options]

=head1 OPTIONS

=over 8

=item B<-r|--rebuild>

Rebuild completely the reporting.

=item B<-s|--start-period>

The reporting rebuild period starts at the indicated date. Example: 2011-09-20.

=item B<-e|--end-period>

The reporting rebuild period ends at the indicated date. Example: 2011-09-21.

=item B<--host-only>

Rebuild only reporting for hosts.

=item B<--service-only>

Rebuild only reporting for services.

=item B<--config>

Specify the path to the main configuration file (default: /etc/centreon/conf.pm).

=item B<--logfile>

Write log messages into this file instead of the standard output.

=item B<--help>

Print a brief help message and exits.

=back

=head1 DESCRIPTION

B<dashboardBuilder> will update dashboard (see in centreon UI).

=cut
