#!/usr/bin/env perl

use warnings;
use centreon::script::nagiosPerfTrace;

centreon::script::nagiosPerfTrace->new()->run();

__END__

=head1 NAME

nagiosPerfTrace - a simple script to manage nagios/centreon-engine stats.

=head1 SYNOPSIS

nagiosPerfTrace [options]

=head1 OPTIONS

=over 8

=item B<--config>

Specify the path to the main configuration file (default: /etc/centreon/conf.pm).

=item B<--logfile>

Write log messages into this file instead of the standard output.

=item B<--help>

Print a brief help message and exits.

=back

=head1 DESCRIPTION

B<nagiosPerfTrace> will get nagios/centreon-engine stats from nagiostats/centenginestats binary
and update RRDs files.

=cut
