#!/usr/bin/env perl

use warnings;
use strict;
use Getopt::Long;
use FindBin qw($Bin);
use lib "$Bin/../lib/perl";
use centreon::common::logger;

use vars qw(@jobs);
my $logger = centreon::common::logger->new();

sub run_task {
    my ($name) = @_;

    if ($name[0] ne '/') {
        $name = "$Bin/../$name";
    }
    $logger->writeLogInfo("$name: start");
    my $output = qx|$name 2>&1|;

    ($? || !defined $output)
      ? $logger->writeLogError("Unexpected end!\n$output")
      : $logger->writeLogInfo($output, withdate => 0);
    $logger->writeLogInfo("$name: stop");
}

=head1 main program

Main program starts here.

=cut

my $cfgfile = "/etc/centreon/nightly_tasks.pm";
my $logfile = "/tmp/$0.log";
my $result = GetOptions("config=s" => \$cfgfile,
                        "logfile=s" => \$logfile);

require $cfgfile;

$logger->file_mode($logfile);
foreach my $task (@jobs) {
    run_task($task);
}
