#!/usr/bin/env perl

use warnings;
use centreon::script::purgeLogs;

centreon::script::purgeLogs->new()->run();

__END__

=head1 NAME

purgeLogs - a simple script to purge logs in database.

=head1 SYNOPSIS

purgeLogs [options]

=head1 OPTIONS

=over 8

=item B<--config>

Specify the path to the main configuration file (default: /etc/centreon/centreon-config.pm).

=item B<--logfile>

Write log messages into this file instead of the standard output.

=item B<--help>

Print a brief help message and exits.

=back

=head1 DESCRIPTION

B<purgeLogs> will get retention information and purge logs in centstorage database.

=cut
