#! /usr/bin/perl -w
################################################################################
# Copyright 2005-2009 MERETHIS
# Centreon is developped by : Julien Mathis and Romain Le Merlus under
# GPL Licence 2.0.
# 
# This program is free software; you can redistribute it and/or modify it under 
# the terms of the GNU General Public License as published by the Free Software 
# Foundation ; either version 2 of the License.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
# PARTICULAR PURPOSE. See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along with 
# this program; if not, see <http://www.gnu.org/licenses>.
# 
# Linking this program statically or dynamically with other modules is making a 
# combined work based on this program. Thus, the terms and conditions of the GNU 
# General Public License cover the whole combination.
# 
# As a special exception, the copyright holders of this program give MERETHIS 
# permission to link this program with independent modules to produce an executable, 
# regardless of the license terms of these independent modules, and to copy and 
# distribute the resulting executable under terms of MERETHIS choice, provided that 
# MERETHIS also meet, for each linked independent module, the terms  and conditions 
# of the license of that module. An independent module is a module which is not 
# derived from this program. If you modify this program, you may extend this 
# exception to your version of the program, but you are not obliged to do so. If you
# do not wish to do so, delete this exception statement from your version.
# 
# For more information : contact@centreon.com
# 
# SVN : $URL: http://svn.centreon.com/trunk/centreon/bin/centSyncTraps $
# SVN : $Id: centSyncTraps 7723 2009-03-11 13:00:05Z jmathis $
#
####################################################################################

use strict;
use warnings;
use DBI;
use File::stat;
use Getopt::Long;
use POSIX;

use vars qw($mysql_user $mysql_password $mysql_host $mysql_db $opt_h $opt_a $data);

$mysql_user = "centreon";
$mysql_password = "";
$mysql_host = "127.0.0.1";
$mysql_db = "ndo";

# Retention in days
my $retention = 60; 

my $dateMax = time() - 60 * 60 * 60 * 24;

## Init Date
my ($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = gmtime(time);

# Init MySQL Connexion
my $dbh = DBI->connect("DBI:mysql:database=".$mysql_db.";host=".$mysql_host, $mysql_user, $mysql_password, {'RaiseError' => 1});

# Comment Purges
my $sth2 = $dbh->prepare("DELETE FROM `nagios_comments` WHERE UNIX_TIMESTAMP(`comment_time`) < '$dateMax'");
if (!$sth2->execute) {
    die "Error:" . $sth2->errstr . "\n";
}

exit();
