platform_topology.add_platform_to_topology:
  methods: POST
  path: /platform_topology
  controller: 'Centreon\Application\Controller\PlatformTopologyController::addPlatformToTopology'
  condition: "request.attributes.get('version.is_beta') == true"
