centreon_security_security_policy_find_security_policy:
    methods: GET
    path: /administration/authentication/local/security-policy
    controller: 'Core\Infrastructure\Security\Api\FindSecurity\FindSecurityPolicyController'
    condition: "request.attributes.get('version') >= 22.04"