Centreon\Domain\Acknowledgement\Acknowledgement:
    properties:
        id:
            type: int
        pollerId:
            type: int
        hostId:
            type: int
            groups: ['ack_host', 'ack_service']
        serviceId:
            type: int
            groups: ['ack_service']
        resourceId:
            type: int
            groups: ['ack_hosts', 'ack_services']
        parentResourceId:
            type: int
            groups: ['ack_services']
        authorId:
            type: int
        comment:
            type: string
        deletionTime:
            type: DateTime
        entryTime:
            type: DateTime
        isNotifyContacts:
            type: bool
        isPersistentComment:
            type: bool
        isSticky:
            type: bool
        state:
            type: int
        withServices:
            type: bool
            groups: ['ack_host_add']
