Centreon\Domain\Acknowledgement\Acknowledgement:
    properties:
        id:
            type: int
            groups:
                - 'ack_main'
                - 'ack_event_list'
        authorId:
            type: int
            groups:
                - 'ack_main'
        comment:
            type: string
            groups:
                - 'ack_main'
                - 'ack_event_list'
        deletionTime:
            type: DateTime
            groups:
                - 'ack_main'
                - 'ack_event_list'
        entryTime:
            type: DateTime
            groups:
                - 'ack_main'
                - 'ack_event_list'
        hostId:
            type: int
            groups:
                - 'ack_main'
        pollerId:
            type: int
            groups:
                - 'ack_main'
        isNotifyContacts:
            type: bool
            groups:
                - 'ack_main'
                - 'ack_event_list'
        isPersistentComment:
            type: bool
            groups:
                - 'ack_main'
                - 'ack_event_list'
        isSticky:
            type: bool
            groups:
                - 'ack_main'
                - 'ack_event_list'
        serviceId:
            type: int
            groups:
                - 'ack_service'
        state:
            type: int
            groups:
                - 'ack_main'
                - 'ack_event_list'