Centreon\Domain\Check\Check:
    properties:
        checkTime:
            type: DateTime
            groups: [Default, check_bulk]
        isForced:
            type: bool
            groups: [Default, check_bulk]
        id:
            type: int
            groups: [check_bulk]
        parentId:
            type: int
            groups: [check_bulk]
        type:
            type: string
            groups: [check_bulk]
