Centreon\Domain\Check\Check:
    properties:
        checkTime:
            type: DateTime
            groups: [Default, check_host, check_service]
        isForced:
            type: bool
            groups: [Default, check_host, check_service]
        id:
            type: int
            groups: [Default, check_host, check_service]
        parentId:
            type: int
            groups: [Default, check_service]
