Centreon\Domain\HostConfiguration\ExtendedHost:
  properties:
    id:
      type: integer
      groups:
        - 'host_extended'
    hostId:
      type: integer
      groups:
        - 'host_extended'
    notes:
      type: string
      groups:
        - 'host_extended'
        - 'host_extended_mapper_simulation'
    notesUrl:
      type: string
      groups:
        - 'host_extended'
        - 'host_extended_mapper_simulation'
    actionsUrl:
      type: string
      groups:
        - 'host_extended'
        - 'host_extended_mapper_simulation'
