Centreon\Domain\HostConfiguration\ExtendedHost:
  properties:
    id:
      type: integer
      groups:
        - 'host_extended'
    hostId:
      type: integer
      groups:
        - 'host_extended'
    notes:
      type: string
      groups:
        - 'host_extended'
        - 'mapper_host_extended'
    notesUrl:
      type: string
      groups:
        - 'host_extended'
        - 'mapper_host_extended'
    actionUrl:
      type: string
      groups:
        - 'host_extended'
        - 'mapper_host_extended'
