Centreon\Domain\Monitoring\ResourceExternalLinks:
    properties:
        actionUrl:
            type: string
            groups:
                - 'resource_status_main'
        notesUrl:
            type: string
            groups:
                - 'resource_status_main'