Centreon\Domain\Monitoring\TimelineEvent:
    virtual_properties:
        getType:
            serialized_name: type
            groups:
                - 'timeline_list'
        getId:
            serialized_name: id
            groups:
                - 'timeline_list'
        getTimestamp:
            serialized_name: date
            groups:
                - 'timeline_list'
    properties:
        object:
            groups:
                - 'timeline_list'