Centreon\Domain\PlatformInformation\PlatformInformation:
  properties:
    version:
      type: string
      groups: [platform_information_main, platform_information_limited]
    isRemote:
      type: bool
      groups: [platform_information_main, platform_information_limited]
    isCentral:
      type: bool
      groups: [platform_information_main, platform_information_limited]
    authorizedMaster:
      type: string
      groups: [platform_information_main]
    apiScheme:
      type: string
      groups: [platform_information_main]
    apiPort:
      type: int
      groups: [platform_information_main]
    apiPath:
      type: string
      groups: [platform_information_main]
    apiPeerValidation:
      type: bool
      groups: [platform_information_main]
    apiUsername:
      type: string
      groups: [platform_information_main]