Centreon\Domain\PlatformInformation\PlatformInformation:
  properties:
    version:
      type: string
      groups: [platform_information_main]
    is_remote:
      type: string
      groups: [platform_information_main]
    is_central:
      type: string
      groups: [platform_information_main]
    authorized_master:
      type: string
      groups: [platform_information_main]
    api_scheme:
      type: string
      groups: [platform_information_main]
    api_port:
      type: int
      groups: [platform_information_main]
    api_path:
      type: string
      groups: [platform_information_main]
    api_peer_validation:
      type: string
      groups: [platform_information_main]
    api_username:
      type: string
      groups: [platform_information_main]