Centreon\Domain\PlatformTopology\PlatformTopology:
  properties:
    ip_address:
      type: string
      groups: [platform_topology_main]
    hostname:
      type: int
      groups: [platform_topology_main]
    server_type:
      type: string
      groups: [platform_topology_main]
    parent:
      type: string
      groups: [platform_topology_main]