Centreon\Domain\Proxy\Proxy:
    properties:
        url:
            type: string
        port:
            type: int
        user:
            type: string
        password:
            type: string