#!/usr/bin/env bash

# Use default variables.
. "$BASE_DIR/tmpl/vardistrib/defaults"

# Set platform-specific directories.
PLUGIN_DIR="/usr/lib64/nagios/plugins"

PEAR_PATH="/opt/rh/rh-php71/root/usr/share/pear"

PHP_BIN="/opt/rh/rh-php71/root/usr/bin/php"
