#!/usr/bin/env bash

# Use default variables.
. "$BASE_DIR/tmpl/vardistrib/defaults"

# Set platform-specific directories.
PLUGIN_DIR="/usr/lib64/nagios/plugins"

PEAR_PATH="/usr/share/pear"

PHP_BIN="/usr/bin/php"
