#!/usr/bin/env bash

# Preconfigured variables, most of them compatible with Unix-like systems.

# Configuration variables.
INSTALL_DIR_CENTREON="/usr/local/share/centreon"
CENTREON_LOG="/var/log/centreon"
CENTREON_ETC="/usr/local/etc/centreon"
CENTREON_RUNDIR="/var/run/centreon"
CENTREON_GENDIR="/var/cache/centreon"
CENTREON_VARLIB="/var/lib/centreon"
CENTSTORAGE_RRD="/var/lib/centreon"
CENTPLUGINS_TMP="/var/lib/centreon/centplugins"
CENTREON_USER="centreon"
CENTREON_GROUP="centreon"
PLUGIN_DIR="/usr/lib/nagios/plugins"
CENTREON_BINDIR="/usr/local/bin"
MONITORINGENGINE_BINARY="/usr/sbin/centengine"
MONITORINGENGINE_INIT_SCRIPT="/usr/sbin/service centengine"
MONITORINGENGINE_ETC="/etc/centreon-engine"
MONITORINGENGINE_LOG="/var/log/centreon-engine"
MONITORINGENGINE_USER="centreon-engine"
BROKER_ETC="/etc/centreon-broker"
BROKER_INIT_SCRIPT="/usr/sbin/service cbd"
BROKER_USER="centreon-broker"

# Install script behavior.
PROCESS_CENTREON_PLUGINS=1
FORCE_SUDO_CONF=1
APACHE_RELOAD=1
PEAR_AUTOINST=1
CENTCORE_INSTALL_INIT=1
CENTCORE_INSTALL_RUNLVL=1
CENTREONTRAPD_INSTALL_INIT=1
