#!/usr/bin/env bash

# Preconfigured variables, most of them compatible with Unix-like systems.

# Configuration variables.
INSTALL_DIR_CENTREON="/usr/share/centreon"
CENTREON_LOG="/var/log/centreon"
CENTREON_ETC="/etc/centreon"
CENTREON_RUNDIR="/var/run/centreon"
CENTREON_CACHEDIR="/var/cache/centreon"
CENTREON_VARLIB="/var/lib/centreon"
CENTSTORAGE_RRD="/var/lib/centreon"
CENTPLUGINS_TMP="/var/lib/centreon/centplugins"
CENTREON_USER="centreon"
CENTREON_GROUP="centreon"
PLUGIN_DIR="/usr/lib/nagios/plugins"
CENTREON_PLUGINS="/usr/lib/centreon/plugins"
CENTREON_BINDIR="/usr/share/centreon/bin"
CENTSTORAGE_BINDIR="/usr/share/centreon/bin"
CENTCORE_BINDIR="/usr/share/centreon/bin"
CENTREONTRAPD_BINDIR="/usr/share/centreon/bin"
MONITORINGENGINE_BINARY="/usr/sbin/centengine"
MONITORINGENGINE_ETC="/etc/centreon-engine"
MONITORINGENGINE_LOG="/var/log/centreon-engine"
MONITORINGENGINE_USER="centreon-engine"
BROKER_ETC="/etc/centreon-broker"
BROKER_USER="centreon-broker"
GORGONE_VARLIB="/var/lib/centreon-gorgone"
GORGONE_CONFIG="/etc/centreon-gorgone"
GORGONE_USER="centreon-gorgone"
GORGONE_GROUP="centreon-gorgone"
SUDO_FILE="/etc/sudoers.d/centreon"
SNMP_ETC="/etc/snmp"
PEAR_PATH="/usr/share/pear"
SERVICE_BINARY="/usr/sbin/service"

PHP_BIN="/usr/bin/php"

# Install script behavior.
PROCESS_CENTREON_WWW=1
PROCESS_CENTSTORAGE=1
PROCESS_CENTCORE=1
PROCESS_CENTREON_PLUGINS=1
PROCESS_CENTREON_SNMP_TRAPS=1
FORCE_SUDO_CONF=1
APACHE_RELOAD=1
PHP_FPM_RELOAD=1
PEAR_AUTOINST=1
CENTCORE_INSTALL_INIT=1
CENTCORE_INSTALL_RUNLVL=1
CENTREONTRAPD_INSTALL_INIT=1
