---
centreon_application_monitoring_services_find_categories:
    methods: "GET"
    path: "/monitoring/services/categories"
    controller: >-
        Core\Category\RealTime\Infrastructure\Api\FindServiceCategory\FindServiceCategoryController
    condition: "request.attributes.get('version') >= 22.10"
centreon_application_monitoring_host_find_categories:
    methods: "GET"
    path: "/monitoring/hosts/categories"
    controller: >-
        Core\Category\RealTime\Infrastructure\Api\FindHostCategory\FindHostCategoryController
    condition: "request.attributes.get('version') >= 22.10"
