monitoring.metric.getServiceMetrics:
    methods: GET
    path: /monitoring/hosts/{hostId}/services/{serviceId}/metrics/start/{start}/end/{end}
    requirements:
        hostId: '\d+'
        serviceId: '\d+'
        start: '\S+'
        end: '\S+'
    controller: 'Centreon\Application\Controller\Monitoring\MetricController::getServiceMetrics'
    condition: "request.attributes.get('version') >= 2.0"

monitoring.metric.getServiceStatus:
    methods: GET
    path: /monitoring/hosts/{hostId}/services/{serviceId}/status/start/{start}/end/{end}
    requirements:
        hostId: '\d+'
        serviceId: '\d+'
        start: '\S+'
        end: '\S+'
    controller: 'Centreon\Application\Controller\Monitoring\MetricController::getServiceStatus'
    condition: "request.attributes.get('version') >= 2.0"
