<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_App-DB-MySQLApp-DB-MySQ_1</name>
   <tag></tag>
   <elementGuidId>9e41daf4-966c-46d4-8592-c24c8dc8e645</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tpSelect_1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>select-one</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tpSelect[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	
	App-DB-MySQL
	App-DB-MySQL-custom
	App-Monitoring-Centreon-Central
	App-Monitoring-Centreon-Central-custom
	App-Monitoring-Centreon-Database
	App-Monitoring-Centreon-Database-custom
	App-Monitoring-Centreon-Poller
	App-Monitoring-Centreon-Poller-custom
	generic-active-host
	generic-active-host-custom
	generic-passive-host
	generic-passive-host-custom
	hostTemplate
	OS-Linux-SNMP
	OS-Linux-SNMP-custom
</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tpSelect_1&quot;)</value>
   </webElementProperties>
</WebElementEntity>
