export const SET_BA_CONFIGURATION = "@bam/SET_BA_CONFIGURATION";
export const BA_CONFIGURATION_CHANGED = "@bam/BA_CONFIGURATION_CHANGED";

export const SET_BA_CONFIGURATION_ERRORS = "@bam/SET_BA_CONFIGURATION_ERRORS";
export const BA_CONFIGURATION_ERRORS = "@bam/BA_CONFIGURATION_ERRORS";
export const RESET_BA_CONFIGURATION_ERRORS = "@bam/RESET_BA_CONFIGURATION_ERRORS";
export const REMOVE_BA_CONFIGURATION_ERROR = "@bam/REMOVE_BA_CONFIGURATION_ERROR";

