<h5>Indicators</h5><hr>
<h6>Service</h6>
<ul>
 {{#indicators.service}}
 <li>{{.}}</li>
 {{/indicators.service}}
</ul>
<hr>
<h6>Metaservice</h6>
<ul>
 {{#indicators.metaservice}}
 <li>{{.}}</li>
 {{/indicators.metaservice}}
</ul>
<h6>Business activity</h6>
<ul>
 {{#indicators.ba}}
 <li>{{.}}</li>
 {{/indicators.ba}}
</ul>
<hr>
<h6>Boolean</h6>
<ul>
 {{#indicators.boolean}}
 <li>{{.}}</li>
 {{/indicators.boolean}}
</ul>
