#!/bin/sh
###################################################################
# Centreon is developped with GPL Licence 2.0 
#
# GPL License: http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt
#
# Developped by : Julien Mathis - Romain Le Merlus 
# Contribute	: Guillaume Watteeux - Maximilien Bersoult
#
###################################################################
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
#    For information : infos@centreon.com
####################################################################
# SVN: $Id$
#
# redefine install command in cinstall (for centreon install script)

#set -x

###
## log: print message
##
## <code>
## log "hello word !"
## </code>
##
## param	$@	message
##
function log() {
	if [ $verbose -eq 1 ] ; then 
		local program=$program
		local message=$@
		echo -e "[$program]: $message"
	fi
	return 0
}

###
## lchown: change username and group
##
## it use global $username and $group
##
## <code>
## lchown /tmp/centreon
## </code>
##
## param	$1	directory
## param	$2	chown/chgrp option (-R)
##
function lchown() {
	local directory="$1"
	local option=$2
	log "lchown: directory: $directory, option: $option"
	if [ -n "$username" ] ; then
		chown $option $username:$group $directory
		log "\tchown $option $username:$group $directory"
	elif [ -n "$group" ] ; then
		chgrp $option $group $directory
		log "\tchgrp $option $group $directory"
	else
		return 0
	fi
	return 0
}

###
## find_and_chmod: find and chmod file or direcoty
##
## <code>
## find_and_chmod /tmp/centreon "d" "775" "1"
## </code>
##
## param	$1	directory
## param	$2	type of search:	f=file
##					d=directory
## param	$3	permission mode
## param	$4	define mindepth in find command (default 0)
##
function find_and_chmod() {
	local directory=$1
	local type=$2
	local mode=$3
	local depth=${4:-0}
	log "find_and_chmod: directory: $directory"
	log "\ttype: $type; mode: $mode; depth: $depth"
	find $directory -mindepth $depth -type $type -print | \
		xargs -I '{}' chmod $mode '{}'
	
	log "\tfind $directory -mindepth $depth -type $type -print | \ "
	log "\t\txargs -I '{}' chmod $mode '{}'"
	return 0
}

###
## usage: print usage of script
##
function usage() {
	local program=cinstall
	cat << __EOT__

Usage: $program [OPTION]... SOURCE DEST
   or: $program [OPTION]... DIRECTORY

In the first form, copy SOURCE to DEST or multiple SOURCE(s) to
the existing DIRECTORY, while setting permission modes and owner/group.
In the second form, create all components of the given DIRECTORY.

Options:
  -u USER	set ownership (super-user only)
  -g GROUP	set group ownership
  -m NUM	set permission mode for file(s) (as in chmod)
  -d NUM	set permission mode for directory(ies) (as in chmod)
  -b BKPDIR	make a backup of each existing destination
  -p BASEDIR	use SOURCE in BASEDIR to set a destination permissions
  -h		display this help and exit
  -v		verbose mode


__EOT__
return 0
}

## Init default variables
program=`basename $0`
username=""
group=""
mode=""
dirmode=""
backupdir=""
backup=0
verbose=0

while getopts ":u:g:m:d:b:p:hv" Option ; do
	#log "Option: $Option, arg: $OPTARG"
	case $Option in
		u )	username="$OPTARG" ;;
		g )	group="$OPTARG" ;;
		m )	mode="$OPTARG" ;;
		d )	dirmode="$OPTARG" ;;
		p )	basedir="$OPTARG" ;;
		b )	backupdir="$OPTARG" ; backup=1 ;;
		v )	verbose=1 ;;
		\?|h )	usage ; exit 0 ;;
		* )	usage ; exit 0 ;;
	esac 
done
shift $(($OPTIND - 1))

[ $# -eq 0 ] && usage && exit 0
## Check if backupdir exists when backup enabled
if [ $backup -eq 1 ] ; then
	log "Backup enabled in $backupdir"
	if [ ! -d $backupdir ] ; then
		log "$backupdir not found"
		mkdir -p $backupdir
		log "$backupdir create"
	fi
fi

### Main

if [ $# -eq 1 ] ; then
	dst=$1
	if [ ! -d $dst ] ; then 
		mkdir -p $dst
		log "Create directory: $dst"
	fi

	## Apply chown on DEST
	lchown $dst

	if [ -n "$dirmode" ] ; then 
		if [ -n "$basedir" ] ; then 
			find_and_chmod $basedir "d" "$dirmode" "1"
		else 
			chmod $dirmode $dst
		fi
	fi
fi
if [ $# -ge 2 ] ; then
	src=$1
	dst=""
	count=1
	shift
	## Count number of arguments
	while [ $# -gt 1 ] ; do
		src="$src $1"
		(( count++ ))
		shift
	done
	dst=$1
	
	## Test if I want exit program...
	## SRC=file and DEST=directory
	## DEST=directory without backup...
	if [ $count -eq 1 -a -d $dst ] ; then
		if [ -f "$src" ] ; then
			log "ERR: count:$count, $src is a file and $dst exists"
			exit 1
		elif [ -d "$src" -a $backup -ne 1 ] ; then
			log "ERR: count:$count, $src is a directory and backup disabled"
			exit 1
		fi
	fi
	
	## Backup DEST if necessary
	if [ $backup -eq 1 -a -e $dst ] ; then
		bdate=`date +%Y%m%d-%H%M%S`
		mv $dst $backupdir/`basename $dst`.$bdate 
		log "Backup $dst in $backupdir/`basename $dst`.$bdate"
	fi

	[ ! -d `dirname $dst` ] && mkdir -p `dirname $dst`
	[ $count -gt 1 -a ! -d $dst ] && mkdir -p $dst
	
	## Test howto copy SRC into DEST
	if [ $count -eq 1 -a -f "$src" ] ; then
		cp $src $dst
		log "count: $count, src: $src, src = file"
		log "cp $src $dst"
	elif [ $count -gt 1 ] ; then 
		cp -R $src $dst
		log "count: $count, src: $src"
		log "cp -R $src $dst"
	elif [ $count -eq 1 -a -d "$src" ] ; then
		cp -R $src $dst
		log "count: $count, src: $src"
		log "cp -R $src $dst"
	else 
		log "No copy"
		log "count: $count, src: $src"
		exit 1
	fi

	
	if [ -n "$basedir" ] ; then 
		## find all file for post set permissions
		cd $basedir
		files=`mktemp -t cinstall_files.XXXXXX`
		directory=`mktemp -t cinstall_dirs.XXXXXX`
		find . -type f -print > $files
		find . -mindepth 1 -type d -print  > $directory
		
		cd $dst
		## Apply permissions
		if [ -n "$username" ] ; then
			cat $files $directory | \
				xargs -I '{}' chown $username:$group '{}' 
		elif [ -n "$group" ] ; then
			cat  $files $directory | \
				xargs -I '{}' chgrp $group '{}'
		fi
		[ -n "$mode" ] && cat $files | \
			xargs -I '{}' chmod $mode '{}' 
		[ -n "$dirmode" ] && cat $directory | \
			xargs -I '{}' chmod $dirmode '{}' 

		rm -f $files $directory
	else 
		if [ $count -eq 1 -a -f "$src" ] ; then
			lchown $dst
			[ -n "mode" ] && chmod $mode $dst
		elif [ $count -eq 1 -a -d "$src" ] ; then
			lchown $dst "-R"
			[ -n "$mode" ] && find_and_chmod $dst "f" "$mode"
			[ -n "$dirmode" ] && find_and_chmod $dst "d" "$dirmode"
		elif [ $count -gt 1 ] ; then
			lchown "$dst/*" "-R"
			[ -n "$mode" ] && find_and_chmod $dst "f" "$mode" "1"
			[ -n "$dirmode" ] && find_and_chmod $dst "d" "$dirmode" "1"

		fi

	fi
fi
exit 0



