#!/bin/bash 

#----
## @Synopsis	This file contains functions to be used by Centreon install scripts
## @Copyright	Copyright 2008, Guillaume Watteeux
## @Licence	GPLv2
## This file contains functions to be used by Centreon install scripts
#----

#################################
# SVN: $Id$

# debug ?
#set -x

## VARS
yes="$(gettext "y")"
no="$(gettext "n")"
ok="$(gettext "OK")"
fail="$(gettext "FAIL")"
passed="$(gettext "PASSED")"
warning="$(gettext "WARNING")"
critical="$(gettext "CRITICAL")"
# Init binary to empty to use pathfind or manual define
GREP=""
CAT=""
SED=""
CHMOD=""
CHOWN=""

## COLOR FUNCTIONS

RES_COL="60"
MOVE_TO_COL="\\033[${RES_COL}G"
SETCOLOR_INFO="\\033[1;38m"
SETCOLOR_SUCCESS="\\033[1;32m"
SETCOLOR_FAILURE="\\033[1;31m"
SETCOLOR_WARNING="\\033[1;33m"
SETCOLOR_NORMAL="\\033[0;39m"

#----
## print info message
## add info message to log file
## @param	message info
## @param	type info (ex: INFO, username...)
## @Stdout	info message
## @Globals	LOG_FILE
#----
function echo_info() {
    echo -e "${1}${MOVE_TO_COL}${SETCOLOR_INFO}${2}${SETCOLOR_NORMAL}" 
    echo -e "$1 : $2" >> $LOG_FILE
}

#----
## Trim whitespaces and tabulations
## @param	string to trim
## @return	string
#----
function trim() {    
    echo "$1" | sed 's/^[ \t]*\(.*\)[ \t]*$/\1/'
}

#----
## print success message
## add success message to log file
## @param	message
## @param	word to specify success (ex: OK)
## @Stdout	success message
## @Globals	LOG_FILE
#----
function echo_success() {
    echo -e "${1}${MOVE_TO_COL}${SETCOLOR_SUCCESS}${2}${SETCOLOR_NORMAL}" 
    echo -e "$1 : $2" >> $LOG_FILE
}

#----
## print failure message
## add failure message to log file
## @param	message
## @param	word to specify failure (ex: fail)
## @Stdout	failure message
## @Globals	LOG_FILE
#----
function echo_failure() {
    echo -e "${1}${MOVE_TO_COL}${SETCOLOR_FAILURE}${2}${SETCOLOR_NORMAL}"
    echo -e "$1 : $2" >> $LOG_FILE
}

#----
## print passed message
## add passed message to log file
## @param	message
## @param	word to specify pass (ex: passed)
## @Stdout	passed message
## @Globals	LOG_FILE
#----
function echo_passed() {
    echo -e "${1}${MOVE_TO_COL}${SETCOLOR_WARNING}${2}${SETCOLOR_NORMAL}"
    echo -e "$1 : $2" >> $LOG_FILE
}

#----
## print warning message
## add warning message to log file
## @param	message
## @param	word to specify warning (ex: warn)
## @Stdout	warning message
## @Globals	LOG_FILE
#----
function echo_warning() {
    echo -e "${1}${MOVE_TO_COL}${SETCOLOR_WARNING}${2}${SETCOLOR_NORMAL}"
    echo -e "$1 : $2" >> $LOG_FILE
}

#----
## add message on log file
## @param	type of message level (debug, info, ...)
## @param	message
## @Globals	LOG_FILE
#----
function log() {
	local program="$0"
	local type="$1"
	shift
	local message="$@"
	echo -e "[$program]:$type: $message" >> $LOG_FILE
}


# FUNCTIONS
#----
## find in $PATH if binary exist
## @param	file to test
## @return 0	found
## @return 1	not found
## @Globals	PATH
#----
function pathfind() {
	OLDIFS="$IFS"
	IFS=:
	for p in $PATH; do
		if [ -x "$p/$*" ]; then
			IFS="$OLDIFS"
			return 0
		fi
	done
	IFS="$OLDIFS"
	return 1
}

#----
## find in $PATH if binary exist and return dirname
## @param	file to test
## @param	global variable to set a result
## @return 0	found
## @return 1	not found
## @Globals	PATH
#----
function pathfind_ret() {
	local bin=$1
	local var_ref=$2
	local OLDIFS="$IFS"
	IFS=:
	for p in $PATH; do
		if [ -x "$p/$bin" ]; then
			IFS="$OLDIFS"
			eval $var_ref=$p
			return 0
		fi
	done
	IFS="$OLDIFS"
	return 1
}

#----
## define a specific variables for grep,cat,sed,... binaries
## This functions was been use in first line on your script
## @return 0	All is't ok
## @return 1	problem with one variable
## @Globals	GREP, CAT, SED, CHMOD, CHOWN
#----
function define_specific_binary_vars() {
	local vars_bin="GREP CAT SED CHMOD CHOWN"
	local var_bin_tolower=""
	for var_bin in $vars_bin ; do
		if [ -z $(eval echo \$$var_bin) ] ; then
			var_bin_tolower="$(echo $var_bin | tr [:upper:] [:lower:])"
			pathfind_ret "$var_bin_tolower" "$(echo -n $var_bin)"
			if [ "$?" -eq 0 ] ; then
				eval "$var_bin='$(eval echo \$$var_bin)/$var_bin_tolower'"
				export $(echo $var_bin)
				log "INFO" "$var_bin=$(eval echo \$$var_bin)"
			else
				return 1
			fi
		fi
	done
	return 0
}

#----
## make a question with yes/no possiblity
## use "no" response by default
## @param	message to print
## @param 	default response (default to no)
## @return 0 	yes
## @return 1 	no
#----
function yes_no_default() {
	local message=$1
	local default=${2:-$no}
	local res="not_define"
	while [ "$res" != "$yes" ] && [ "$res" != "$no" ] && [ ! -z "$res" ] ; do
		echo -e "\n$message\n$(gettext "[y/n], default to [$default]:")"
		echo -en "> "
		read res
		[ -z "$res" ] && res="$default"
	done
	if [ "$res" = "$yes" ] ; then 
		return 0
	else 
		return 1
	fi
}

#----
## print a message, test directory if answer is correct 
## Loop if not a valid directory
## @param	message
## @param	default value (use "NO_DEFAULT" if not default value)
## @param	global variable to set a result
## @return 0	end
#----
function answer_with_testdir() {
	local message=$1
	local default=$2
	local var_ref=$3
	local res="not_define"
	local first=0
	while [ ! -d "$res" ] ; do
		[ $first -eq 1 ] && echo_passed "$(gettext "$res is not a directory or does not exist.")" "$critical" 
		echo -e "\n$message"
		[ "$default" != "NO_DEFAULT" ] && echo -e "$(gettext "default to [$default]")"
		echo -en "> "
		read res
		if [ -z "$res" ] ; then 
			[ $default != "NO_DEFAULT" ] && res=$default
		fi
		if [ -z ${res#/} ] ; then
			echo_passed  "$(gettext "You select slash...")"
			res="not_define"
		else
			first=1
		fi
	done
	eval $var_ref=$res
	return 0
}

#----
## print a message, create directory with answer 
## Loop if not a valid directory (slash...)
## @param	message
## @param	default value (use "NO_DEFAULT" if not default value)
## @param	global variable to set a result
## @return 0	end
#----
function answer_with_createdir() {
	local message=$1
	local default=$2
	local var_ref=$3
	local res="not_define"
	local first=0
	while [ ! -d "$res" ] ; do
		[ $first -eq 1 ] && echo_passed "$(gettext "Directory $res does not exists.")" "$critical"
		echo -e "\n$message"
		[ "$default" != "NO_DEFAULT" ] && echo -e "$(gettext "default to") [$default]"
		echo -en "> "
		read res
		if [ -z "$res" ] ; then
			[ "$default" != "NO_DEFAULT" ] && res=$default
		fi
		if [ -z "${res#/}" -o "$yes" = "$res" -o "$no" = "$res" ] ; then
			echo_passed  "$(gettext "You select slash...")"
			res="not_define"
		else 
			first=1
			[ -d "$res" ] && break 
			yes_no_default "$(gettext "Do you want me to create this directory ?") [$res]"
			if [ $? -eq 0 ] ; then
				mkdir -p $res
				if [ $? -ne 0 ] ; then
					echo_passed "$(gettext "Could not create directory.")" "$critical"
					#continue
				fi
				log "INFO" "$(gettext "Creating") : $res"
			fi
		fi
	done
	eval $var_ref=$res
	return 0
}

#----
## print a message, test if file exists 
## Loop if not a valid file 
## @param	message
## @param	default value (use "NO_DEFAULT" if not default value)
## @param	global variable to set a result
## @return 0	end
#----
function answer_with_testfile() {
	local message=$1
	local default=$2
	local var_ref=$3
	local res="not_define"
	local first=0
	while [ ! -f "$res" ] ; do
		[ $first -eq 1 ] && echo_passed "$(gettext "$res is not a valid file.")" "$critical" 
		echo -e "\n$message"
		[ "$default" != "NO_DEFAULT" ] && echo -e "$(gettext "default to") [$default]"
		echo -en "> "
		read res
		if [ -z "$res" ] ; then 
			[ "$default" != "NO_DEFAULT" ] && res=$default
		fi
		first=1
	done
	eval $var_ref=$res
	return 0
}

#----
## Test if file exist
## @param	file
## @param	variable to reset
## @return 0 	file exist
## @return 1 	file does not exist
#----
function testfile_clean() {
	local file="$1"
	local var="$2"
	[ -z "$file" ] && return 1
	if [ ! -e "$file" ] ; then
		eval $var=""
		return 1
	else 
		return 0
	fi
}

#----
## Test if directory exist
## @param	directory
## @param	variable to reset
## @return 0 directory exist
## @return 1 directory does not exist
#----
function testdir_clean() {
	local dir="$1"
	local var="$2"
	[ -z "$dir" ] && return 1
	if [ ! -d "$dir" ] ; then
		eval $var=""
		return 1
	else
		return 0
	fi
}

function test_answer() {
	if [ ! -z $2 ] ; then
		if [ $2 != "" ] ; then
			eval $1=$2
		fi
	fi
}

#----
## use to select a data on array 
## set to a variable a result of chose
## @param	variable to set a resutl
## @param	List of possiblity to chose
## @return 0	end
#----
function select_in_array() {
	local variable=$1
	shift
	local array=($@)
	local res=1
	local count=0
	local first=0
	while [ $res -gt $count ] ; do
		[ $first -eq 1 ] && echo_failure "$(gettext "\$res is not a valid response.")" "$critical" 
		count=0
		local limit=${#array[@]}
		for (( datas=0; datas < limit; datas++ )) ; do
			echo -e "\t$datas:\t${array[$datas]}"
			let "count += 1" 
		done
		echo -en "> "
		read res
		first=1
		if [ $res -eq $res 2>/dev/null ] ; then
			echo " " 
		else 
			echo_failure "$(gettext "$res is not an integer")" "$fail"
			res=255
			first=0
		fi
	done
	eval $variable=${array[$res]}
	return 0
}

#----
## Define where nagios is installed
## @Globals	INSTALL_DIR_NAGIOS, DEFAULT_INSTALL_DIR_NAGIOS
#----
function locate_nagios_installdir() {
	testdir_clean "$INSTALL_DIR_NAGIOS" "INSTALL_DIR_NAGIOS" 
	if [ -z "$INSTALL_DIR_NAGIOS" ] ; then
		answer_with_testdir "$(gettext "Where is installed Nagios ?")" "$DEFAULT_INSTALL_DIR_NAGIOS" "INSTALL_DIR_NAGIOS"
		echo_success "$(gettext "Path") $INSTALL_DIR_NAGIOS" "$ok"
	fi
	INSTALL_DIR_NAGIOS=`trim ${INSTALL_DIR_NAGIOS%/}`
	export INSTALL_DIR_NAGIOS
	log "INFO" "INSTALL_DIR_NAGIOS: $INSTALL_DIR_NAGIOS"
}

#----
## Define where is nagios config directory
## @Globals	NAGIOS_ETC, DEFAULT_NAGIOS_ETC
#----
function locate_nagios_etcdir() {
	testdir_clean "$NAGIOS_ETC" "NAGIOS_ETC"
	if [ -z "$NAGIOS_ETC" ] ; then
		answer_with_testdir "$(gettext "Where is your nagios config directory")" "$DEFAULT_NAGIOS_ETC" "NAGIOS_ETC"
		echo_success "$(gettext "Path") $NAGIOS_ETC" "$ok"
	fi
	NAGIOS_ETC=`trim ${NAGIOS_ETC%/}`
	export NAGIOS_ETC
	log "INFO" "NAGIOS_ETC: $NAGIOS_ETC"
}

#----
## Define where is nagios var directory (/var/log)
## @Globals	NAGIOS_VAR, DEFAULT_NAGIOS_VAR
#----
function locate_nagios_vardir() {
	testdir_clean "$NAGIOS_VAR" "NAGIOS_VAR"
	if [ -z "$NAGIOS_VAR" ] ; then
		answer_with_testdir "$(gettext "Where is your Nagios var directory ?")" "$DEFAULT_NAGIOS_VAR" "NAGIOS_VAR"
		echo_success "$(gettext "Path" ) $NAGIOS_VAR" "$ok"
	fi
	NAGIOS_VAR=`trim ${NAGIOS_VAR%/}`
	export NAGIOS_VAR
	log "INFO" "NAGIOS_VAR: $NAGIOS_VAR"
}

#----
## Define where is nagios plugins directory
## in last version of this script, you have been a possibility to create if not exist. now is not possible. You will create manualy.
## @Globals	NAGIOS_PLUGIN, DEFAULT_NAGIOS_PLUGIN
#----
function locate_nagios_plugindir() {
	testdir_clean "$NAGIOS_PLUGIN" "NAGIOS_PLUGIN"
	if [ -z "$NAGIOS_PLUGIN" ] ; then
		answer_with_testdir "$(gettext "Where is your Nagios plugins (libexec) directory ?")" "$DEFAULT_NAGIOS_PLUGIN" "NAGIOS_PLUGIN"
		echo_success "$(gettext "Path" ) $NAGIOS_PLUGIN" "$ok"
	fi
	NAGIOS_PLUGIN=`trim ${NAGIOS_PLUGIN%/}`
	export NAGIOS_PLUGIN
	log "INFO" "NAGIOS_PLUGIN: $NAGIOS_PLUGIN"
}

#----
## Define where is your nagios binary
## By default, use nagios,nagios2 or nagios3 name and find in PATH
## @Globals	NAGIOS_BINARY, DEFAULT_NAGIOS_BINARY
#----
function locate_nagios_binary() {
	testfile_clean "$NAGIOS_BINARY" "NAGIOS_BINARY"
	if [ -z "$NAGIOS_BINARY" ] ; then
		nagios_binaries="nagios nagios2 nagios3"
		for binary in $nagios_binaries ; do
			pathfind_ret "$binary" "NAGIOS_BINARY"
			if [ "$?" -eq 0 ] ; then
				NAGIOS_BINARY="$NAGIOS_BINARY/$binary"
				break
			fi
		done
		if [ -z "$NAGIOS_BINARY" ] ; then 
			answer_with_testfile "$(gettext "Where is your nagios binary ? ")" "$DEFAULT_NAGIOS_BINARY" "NAGIOS_BINARY"
		fi
		echo_success "$NAGIOS_BINARY" "$ok"
	fi
	NAGIOS_BINARY=`trim ${NAGIOS_BINARY%/}`
	export NAGIOS_BINARY
	log "INFO" "NAGIOS_BINARY: $NAGIOS_BINARY"
}

#----
## Define where is your nagiostats binary
## By default, use nagiostats,nagios2stats or nagios3stats name and find in PATH
## @Globals	NAGIOSTATS_BINARY, DEFAULT_NAGIOSTATS_BINARY
#----
function locate_nagiostats_binary() {
	testfile_clean "$NAGIOSTATS_BINARY" "NAGIOSTATS_BINARY"
	if [ -z "$NAGIOSTATS_BINARY" ] ; then
		nagiostats_binaries="nagiostats nagios2stats nagios3stats"
		for binary in $nagiostats_binaries ; do
			pathfind_ret "$binary" "NAGIOSTATS_BINARY"
			if [ "$?" -eq 0 ] ; then
				NAGIOSTATS_BINARY="$NAGIOSTATS_BINARY/$binary"
				break
			fi
		done
		if [ -z "$NAGIOSTATS_BINARY" ] ; then 
			answer_with_testfile "$(gettext "Where is your nagiostats binary ? ")" "$DEFAULT_NAGIOSTATS_BINARY" "NAGIOSTATS_BINARY"
		fi
		echo_success "$NAGIOSTATS_BINARY" "$ok"
	fi
	NAGIOSTATS_BINARY=`trim ${NAGIOSTATS_BINARY%/}`
	export NAGIOSTATS_BINARY
	log "INFO" "NAGIOSTATS_BINARY: $NAGIOSTATS_BINARY"
}

#----
## Define where is a p1.pl file for nagios
## If you use a --enable-embedded-perl options in nagios configure, you'll use
## a p1 file.
## <p>
## This fonction find un nagios etc directory if one config file use p1_file.
## @Globals	NAGIOS_P1_FILE
#----
function locate_nagios_p1_file() {
	testfile_clean "$NAGIOS_P1_FILE" "NAGIOS_P1_FILE"
	local nagios_etc="$1"
	if [ -z "$NAGIOS_P1_FILE" ] ; then 
		NAGIOS_P1_FILE=$(${GREP} -r "^p1_file" $nagios_etc | ${GREP} -v -i "sample" | cut -d= -f2 | uniq )
		if [ -z "$NAGIOS_P1_FILE" ] ; then
			log "INFO" "$(gettext "p1_file not found")"
		else
			is_single "$NAGIOS_P1_FILE"
			if [ "$?" -eq 1 ] ; then
				echo -e "$(gettext "Please select a good nagios p1 file")"
				select_in_array \
					"NAGIOS_P1_FILE" "${NAGIOS_P1_FILE[@]}"
			fi
			log "INFO" "$(gettext "p1_file found") : $NAGIOS_P1_FILE"
			echo_success "p1_file : $NAGIOS_P1_FILE" "$ok"	
		fi
	fi
	NAGIOS_P1_FILE=`trim ${NAGIOS_P1_FILE%/}`
	export NAGIOS_P1_FILE
	log "INFO" "NAGIOS_P1_FILE: $NAGIOS_P1_FILE"
}

#----
## Define where is nagios images directory
## @Globals NAGIOS_IMG, $DEFAULT_NAGIOS_IMG
#----
function locate_nagios_imgdir() {
	testdir_clean "$NAGIOS_IMG" "NAGIOS_IMG"
	if [ -z "$NAGIOS_IMG" ] ; then
		answer_with_testdir "$(gettext "Where is your Nagios image directory ?")" "$DEFAULT_NAGIOS_IMG" "NAGIOS_IMG"
		echo_success "$(gettext "Path" ) $NAGIOS_IMG" "$ok"
	fi
	NAGIOS_IMG=`trim ${NAGIOS_IMG%/}`
	export NAGIOS_IMG
	log "INFO" "NAGIOS_IMG: $NAGIOS_IMG"
}

#----
## Define where is your NDO ndo2db binary
## By default, use ndo2db,ndo2db-2x and ndo2db-3x name and find in PATH
## @Globals	NDO2DB_BINARY, DEFAULT_NDO2DB_BINARY
#----
function locate_ndo2db_binary() {
	testfile_clean "$NDO2DB_BINARY" "NDO2DB_BINARY"
	if [ -z "$NDO2DB_BINARY" ] ; then
		ndo2db_binaries="ndo2db ndo2db-2x ndo2db-3x"
		for binary in $ndo2db_binaries ; do
			pathfind_ret "$binary" "NDO2DB_BINARY"
			if [ "$?" -eq 0 ] ; then
				NDO2DB_BINARY="$NDO2DB_BINARY/$binary"
				break
			fi
		done
		if [ -z "$NDO2DB_BINARY" ] ; then 
			answer_with_testfile "$(gettext "Where is your NDO ndo2db binary ? ")" "$DEFAULT_NDO2DB_BINARY" "NDO2DB_BINARY"
		fi
		echo_success "$NDO2DB_BINARY" "$ok"
	fi
	NDO2DB_BINARY=`trim ${NDO2DB_BINARY%/}`
	export NDO2DB_BINARY
	log "INFO" "NDO2DB_BINARY: $NDO2DB_BINARY"
}

#----
## Define where is your NDO ndomob binary
## By default, use ndomod,ndomod.o,ndomod-2x,ndomod-2x.o,ndomod-3x and ndomod-3x.o name and find in PATH
## @Globals	NDOMOD_BINARY, DEFAULT_NDOMOD_BINARY
#----
function locate_ndomod_binary() {
	testfile_clean "$NDOMOD_BINARY" "NDOMOD_BINARY"
	if [ -z "$NDOMOD_BINARY" ] ; then
		ndomod_binaries="ndomod ndomod.o ndomod-2x ndomod-2x.o ndomod-3x ndomod-3x.o"
		for binary in $ndomod_binaries ; do
			pathfind_ret "$binary" "NDOMOD_BINARY"
			if [ "$?" -eq 0 ] ; then
				NDOMOD_BINARY="$NDOMOD_BINARY/$binary"
				break
			fi
		done
		if [ -z "$NDOMOD_BINARY" ] ; then 
			answer_with_testfile "$(gettext "Where is your NDO ndomod binary ? ")" "$DEFAULT_NDOMOD_BINARY" "NDOMOD_BINARY"
		fi
		echo_success "$NDOMOD_BINARY" "$ok"
	fi
	NDOMOD_BINARY=`trim ${NDOMOD_BINARY%/}`
	export NDOMOD_BINARY
	log "INFO" "NDOMOD_BINARY: $NDOMOD_BINARY"
}

#----
## Define where is your init.d (rc.d) directory
## check on system where is a init.d or rc.d directory to install centreon services
## On GNU/Linux, most of distrib use /etc/init.d
## On FreeBSD, use /usr/local/etc/rc.d
## It's possible to add most of directory.
## @Globals	INIT.D, DEFAULT_INIT_D 
#----
function locate_init_d() {
	testdir_clean "$INIT_D" "INIT_D" 
	if [ -z "$INIT_D" ] ; then
		if [ -d "/etc/init.d" ] ; then
			INIT_D="/etc/init.d"
		elif [ -d "/usr/local/etc/rc.d" ] ; then
			INIT_D="/usr/local/etc/rc.d"
		# Add most of init.d 
		else 
			answer_with_testdir "$(gettext "Where is your init.d directory ?")" "$DEFAULT_INIT_D" "INIT_D"
			echo_success "$(gettext "Path" ) $INIT_D" "$ok"
		fi
	fi
	INIT_D=`trim ${INIT_D%/}`
	export INIT_D
	log "INFO" "INIT_D: $INIT_D"
}

#----
## Define where is Centreon log directory
## @Globals	CENTREON_LOG, DEFAULT_CENTREON_LOG
#----
function locate_centreon_logdir() {
	if [ -z "$CENTREON_LOG" ] ; then
		answer_with_createdir "$(gettext "Where is your Centreon log directory")" "$DEFAULT_CENTREON_LOG" "CENTREON_LOG"
		echo_success "$(gettext "Path" ) $CENTREON_LOG" "$ok"
	elif [ ! -d "$CENTREON_LOG" -a "$silent_install" -eq 1 ] ; then
		mkdir -p "$CENTREON_LOG"
		log "INFO" "$(gettext "Create") $CENTREON_LOG"
	fi
	CENTREON_LOG=`trim ${CENTREON_LOG%/}`
	export CENTREON_LOG
	log "INFO" "CENTREON_LOG: $CENTREON_LOG"
}

#----
## Define where is Centreon etc (config) directory
## @Globals	CENTREON_ETC, DEFAULT_CENTREON_ETC
#----
function locate_centreon_etcdir() {
	if [ -z "$CENTREON_ETC" ] ; then
		answer_with_createdir "$(gettext "Where is your Centreon etc directory")" "$DEFAULT_CENTREON_ETC" "CENTREON_ETC"
		echo_success "$(gettext "Path" ) $CENTREON_ETC" "$ok"
	elif [ ! -d "$CENTREON_ETC" -a "$silent_install" -eq 1 ] ; then
		mkdir -p "$CENTREON_ETC"
		log "INFO" "$(gettext "Create") $CENTREON_ETC"
	fi
	CENTREON_ETC=`trim ${CENTREON_ETC%/}`
	export CENTREON_ETC
	log "INFO" "CENTREON_ETC: $CENTREON_ETC"
}

#----
## Define where is centreon install directory 
## @Globals	INSTALL_DIR_CENTREON, DEFAULT_INSTALL_DIR_CENTREON
#----
function locate_centreon_installdir() {
	if [ -z "$INSTALL_DIR_CENTREON" ] ; then
		answer_with_createdir "$(gettext "Where is your Centreon directory?")" "$DEFAULT_INSTALL_DIR_CENTREON" "INSTALL_DIR_CENTREON"
		echo_success "$(gettext "Path" ) $INSTALL_DIR_CENTREON" "$ok"
	elif [ ! -d "$INSTALL_DIR_CENTREON" -a "$silent_install" -eq 1 ] ; then
		mkdir -p "$INSTALL_DIR_CENTREON"
		log "INFO" "$(gettext "Create") $INSTALL_DIR_CENTREON"
	fi	
	INSTALL_DIR_CENTREON=`trim ${INSTALL_DIR_CENTREON%/}`
	export INSTALL_DIR_CENTREON
	log "INFO" "INSTALL_DIR_CENTREON: $INSTALL_DIR_CENTREON"
}

#----
## Define where is Centreon generation directory
## Generation directory is use for a temporary config of nagios.
## filesUpload and filesGeneration directories
## @Globals	CENTREON_GENDIR, DEFAULT_CENTREON_GENDIR
#----
function locate_centreon_generationdir() {
	if [ -z "$CENTREON_GENDIR" ] ; then
		answer_with_createdir "$(gettext "Where is your Centreon generation_files directory?")" "$DEFAULT_CENTREON_GENDIR" "CENTREON_GENDIR"
		echo_success "$(gettext "Path" ) $CENTREON_GENDIR" "$ok"
	elif [ ! -d "$CENTREON_GENDIR" -a "$silent_install" -eq 1 ] ; then
		mkdir -p "$CENTREON_GENDIR"
		log "INFO" "$(gettext "Create") $CENTREON_GENDIR"
	fi
	CENTREON_GENDIR=`trim ${CENTREON_GENDIR%/}`
	export CENTREON_GENDIR
	log "INFO" "CENTREON_GENDIR: $CENTREON_GENDIR"
}

#----
## Define where is Centreon run directory (for .run file)
## @Globals	CENTREON_RUNDIR, DEFAULT_CENTREON_RUNDIR
#----
function locate_centreon_rundir() {
	if [ -z "$CENTREON_RUNDIR" ] ; then
		answer_with_createdir "$(gettext "Where is your Centreon Run Dir directory?")" "$DEFAULT_CENTREON_RUNDIR" "CENTREON_RUNDIR"
		echo_success "$(gettext "Path" ) $CENTREON_RUNDIR" "$ok"
	elif [ ! -d "$CENTREON_RUNDIR" -a "$silent_install" -eq 1 ] ; then
		mkdir -p "$CENTREON_RUNDIR"
		log "INFO" "$(gettext "Create") $CENTREON_RUNDIR"
	fi
	CENTREON_RUNDIR=`trim ${CENTREON_RUNDIR%/}`
	export CENTREON_RUNDIR
	log "INFO" "CENTREON_RUNDIR: $CENTREON_RUNDIR"
}

#----
## Define where is Centreon variable library directory
## @Globals	CENTREON_VARLIB, DEFAULT_CENTREON_VARLIB
#----
function locate_centreon_varlib() {
	if [ -z "$CENTREON_VARLIB" ] ; then
		answer_with_createdir "$(gettext "Where is your Centreon variable library directory?")" "$DEFAULT_CENTREON_VARLIB" "CENTREON_VARLIB"
		echo_success "$(gettext "Path" ) $CENTREON_VARLIB" "$ok"
	elif [ ! -d "$CENTREON_VARLIB" -a "$silent_install" -eq 1 ] ; then
		mkdir -p "$CENTREON_VARLIB"
		log "INFO" "$(gettext "Create") $CENTREON_VARLIB"
	fi
	CENTREON_VARLIB=`trim ${CENTREON_VARLIB%/}`
	export CENTREON_VARLIB
	log "INFO" "CENTREON_VARLIB: $CENTREON_VARLIB"
}

#----
## Define where centStorage store a RRD file
## @Globals	CENTSTORAGE_RRD, DEFAULT_CENTSTORAGE_RRD
#----
function locate_centstorage_rrddir() {
	if [ -z "$CENTSTORAGE_RRD" ] ; then
		answer_with_createdir "$(gettext "Where is your CentStorage RRD directory")" "$DEFAULT_CENTSTORAGE_RRD" "CENTSTORAGE_RRD"
		echo_success "$(gettext "Path" ) $CENTSTORAGE_RRD" "$ok"
	elif [ ! -d "$CENTSTORAGE_RRD" -a "$silent_install" -eq 1 ] ; then
		mkdir -p "$CENTSTORAGE_RRD"
		log "INFO" "$(gettext "Create") $CENTSTORAGE_RRD"
	fi
	CENTSTORAGE_RRD=`trim ${CENTSTORAGE_RRD%/}`
	export CENTSTORAGE_RRD
	log "INFO" "CENTSTORAGE_RRD: $CENTSTORAGE_RRD"
}

#----
## Define where is centStorage binary directory
## @Globals	CENTSTORAGE_BINDIR, INSTALL_DIR_CENTREON, DEFAULT_CENTSTORAGE_BINDIR
#----
function locate_centstorage_bindir() {
	if [ -z "$CENTSTORAGE_BINDIR" ] ; then
		answer_with_createdir "$(gettext "Where is your CentStorage binary directory")" "$INSTALL_DIR_CENTREON/$DEFAULT_CENTSTORAGE_BINDIR" "CENTSTORAGE_BINDIR"
		echo_success "$(gettext "Path" ) $CENTSTORAGE_BINDIR" "$ok"
	elif [ ! -d "$CENTSTORAGE_BINDIR" -a "$silent_install" -eq 1 ] ; then
		mkdir -p "$CENTSTORAGE_BINDIR"
		log "INFO" "$(gettext "Create") $CENTSTORAGE_BINDIR"
	fi
	CENTSTORAGE_BINDIR=`trim ${CENTSTORAGE_BINDIR%/}`
	export CENTSTORAGE_BINDIR
	log "INFO" "CENTSTORAGE_BINDIR: $CENTSTORAGE_BINDIR"
}

#----
## Define where is centStorage library directory
## @Globals	CENTSTORAGE_LIBDIR, INSTALL_DIR_CENTREON, DEFAULT_CENTSTORAGE_LIBDIR
#----
function locate_centstorage_libdir() {
	if [ -z "$CENTSTORAGE_LIBDIR" ] ; then
		answer_with_createdir "$(gettext "Where is your CentStorage library directory")" "$INSTALL_DIR_CENTREON/$DEFAULT_CENTSTORAGE_LIBDIR" "CENTSTORAGE_LIBDIR"
		echo_success "$(gettext "Path" ) $CENTSTORAGE_LIBDIR" "$ok"
	elif [ ! -d "$CENTSTORAGE_LIBDIR" -a "$silent_install" -eq 1 ] ; then
		mkdir -p "$CENTSTORAGE_LIBDIR"
		log "INFO" "$(gettext "Create") $CENTSTORAGE_LIBDIR"
	fi
	CENTSTORAGE_LIBDIR=`trim ${CENTSTORAGE_LIBDIR%/}`
	export CENTSTORAGE_LIBDIR
	log "INFO" "CENTSTORAGE_LIBDIR: $CENTSTORAGE_LIBDIR"
}

#----
## Define where is centCore binary directory
## @Globals	CENTCORE_BINDIR, INSTALL_DIR_CENTREON, DEFAULT_CENTCORE_BINDIR
#----
function locate_centcore_bindir() {
	if [ -z "$CENTCORE_BINDIR" ] ; then
		answer_with_createdir "$(gettext "Where is your CentCore binary directory")" "$INSTALL_DIR_CENTREON/$DEFAULT_CENTCORE_BINDIR" "CENTCORE_BINDIR"
		echo_success "$(gettext "Path" ) $CENTCORE_BINDIR" "$ok"
	elif [ ! -d "$CENTCORE_BINDIR" -a "$silent_install" -eq 1 ] ; then
		mkdir -p $CENTCORE_BINDIR
		log "INFO" "$(gettext "Create") $CENTCORE_BINDIR"
	fi
	CENTCORE_BINDIR=`trim ${CENTCORE_BINDIR%/}`
	export CENTCORE_BINDIR
	log "INFO" "CENTCORE_BINDIR: $CENTCORE_BINDIR"
}

#----
## Define where is centPlugins temporary directory
## @Globals	CENTPLUGINS_TMP, DEFAULT_CENTPLUGINS_TMP
#----
function locate_centplugins_tmpdir() {
	if [ -z "$CENTPLUGINS_TMP" ] ; then
		answer_with_createdir "$(gettext "Where is your CentPlugins lib directory")" "$DEFAULT_CENTPLUGINS_TMP" "CENTPLUGINS_TMP"
		echo_success "$(gettext "Path" ) $CENTPLUGINS_TMP" "$ok"
	elif [ ! -d "$CENTPLUGINS_TMP" -a "$silent_install" -eq 1 ] ; then
		mkdir -p "$CENTPLUGINS_TMP"
		log "INFO" "$(gettext "Create") $CENTPLUGINS_TMP"
	fi
	CENTPLUGINS_TMP=`trim ${CENTPLUGINS_TMP%/}`
	export CENTPLUGINS_TMP
	log "INFO" "CENTPLUGINS_TMP: $CENTPLUGINS_TMP"
}

#----
## Define where is centPluginsTraps binary directory
## @Globals	CENTPLUGINSTRAPS_BINDIR, DEFAULT_CENTPLUGINSTRAPS_BINDIR
#----
function locate_centpluginstraps_bindir() {
	if [ -z "$CENTPLUGINSTRAPS_BINDIR" ] ; then
		answer_with_createdir "$(gettext "Where is your CentPlugins Traps binary")" "$DEFAULT_CENTPLUGINSTRAPS_BINDIR" "CENTPLUGINSTRAPS_BINDIR"
		echo_success "$(gettext "Path" ) $CENTPLUGINSTRAPS_BINDIR" "$ok"
	elif [ ! -d "$CENTPLUGINSTRAPS_BINDIR" -a "$silent_install" -eq 1 ] ; then
		mkdir -p "$CENTPLUGINSTRAPS_BINDIR"
		log "INFO" "$(gettext "Create") $CENTPLUGINSTRAPS_BINDIR"
	fi
	CENTPLUGINSTRAPS_BINDIR=`trim ${CENTPLUGINSTRAPS_BINDIR%/}`
	export CENTPLUGINSTRAPS_BINDIR
	log "INFO" "CENTPLUGINSTRAPS_BINDIR: $CENTPLUGINSTRAPS_BINDIR"
}

#----
## Define where is SNMP etc (config) directory
## @Globals	SNMP_ETC, DEFAULT_SNMP_ETC
#----
function locate_snmp_etcdir() {
	testdir_clean "$SNMP_ETC" "SNMP_ETC"
	if [ -z "$SNMP_ETC" ] ; then
		answer_with_testdir "$(gettext "Where is your SNMP configuration directory")" "$DEFAULT_SNMP_ETC" "SNMP_ETC"
		echo_success "$SNMP_ETC" "$ok"
	fi
	SNMP_ETC=${SNMP_ETC%/}
	export SNMP_ETC
	log "INFO" "SNMP_ETC: $SNMP_ETC"
}

#----
## Define where is SNMPTT binary directory
## @Globals	SNMPTT_BINDIR, DEFAULT_SNMPTT_BINDIR
#----
function locate_snmptt_bindir() {
	if [ -z "$SNMPTT_BINDIR" ] ; then
		answer_with_createdir "$(gettext "Where is your SNMPTT binaries directory")" "$DEFAULT_SNMPTT_BINDIR" "SNMPTT_BINDIR"
		echo_success "$SNMPTT_BINDIR" "$ok"
	fi
	SNMPTT_BINDIR=`trim ${SNMPTT_BINDIR%/}`
	export SNMPTT_BINDIR
	log "INFO" "SNMPTT_BINDIR: $SNMPTT_BINDIR"
}

#----
## Define where is Sudo file
## @Globals	SUDO_FILE, DEFAULT_SUDO_FILE
#----
function locate_sudo() {
	testfile_clean "$SUDO_FILE" "SUDO_FILE"
	if [ -z "$SUDO_FILE" ] ; then
		answer_with_testfile "$(gettext "Where is sudo configuration file")" "$DEFAULT_SUDO_FILE" "SUDO_FILE"
		echo_success "$SUDO_FILE" "$ok"
	fi
	SUDO_FILE=`trim ${SUDO_FILE%/}`
	export SUDO_FILE
	log "INFO" "SUDO_FILE: $SUDO_FILE"
}

#----
## Define where is Perl RRD file (RRDs.pm)
## @Globals	RRD_PERL, DEFAULT_RRD_PERL
#----
function locate_rrd_perldir() {
	testdir_clean "$RRD_PERL" "RRD_PERL"
	if [ -z "$RRD_PERL" ] ; then
		answer_with_testfile "$(gettext "Where is the RRD perl module installed [RRDs.pm]")" "$DEFAULT_RRD_PERL/RRDs.pm" "RRD_PERL"
		RRD_PERL=$(dirname $RRD_PERL)
		echo_success "$(gettext "Path" ) $RRD_PERL" "$ok"
	fi
	RRD_PERL=`trim ${RRD_PERL%/}`
	export RRD_PERL
	log "INFO" "RRD_PERL: $RRD_PERL"
}

#----
## Define where is rrdtool binary
## find rrdtool in PATH
## @Globals	BIN_RRDTOOL, DEFAULT_BIN_RRDTOOL
#----
function locate_rrdtool() {
	testfile_clean "$BIN_RRDTOOL" "BIN_RRDTOOL"
	if [ -z "$BIN_RRDTOOL" ] ; then 
		pathfind_ret "rrdtool" "BIN_RRDTOOL"
		if [ "$?" -ne 0 ] ; then 
			answer_with_testfile "$(gettext "Where is rrdtool")" "$DEFAULT_BIN_RRDTOOL" "BIN_RRDTOOL"
		else 
			BIN_RRDTOOL="$BIN_RRDTOOL/rrdtool"
		fi
		echo_success "$BIN_RRDTOOL" "$ok"
	fi
	BIN_RRDTOOL=`trim ${BIN_RRDTOOL%/}`
	export BIN_RRDTOOL
	log "INFO" "BIN_RRDTOOL: $BIN_RRDTOOL"
}

#----
## Define where is perl binary
## find perl in PATH
## @Globals	BIN_PERL, DEFAULT_BIN_PERL
#----
function locate_perl() {
	testfile_clean "$BIN_PERL" "BIN_PERL"
	if [ -z "$BIN_PERL" ] ; then 
		pathfind_ret "perl" "BIN_PERL"
		if [ "$?" -ne 0 ] ; then 
			answer_with_testfile "$(gettext "Where is perl")" "$DEFAULT_BIN_PERL" "BIN_PERL"
		else 
			BIN_PERL="$BIN_PERL/perl"
		fi
		echo_success "$BIN_PERL" "$ok"
	fi
	BIN_PERL=`trim ${BIN_PERL%/}`
	export BIN_PERL
	log "INFO" "BIN_PERL: $BIN_PERL"
}

#----
## Define where is mail binary
## find mail in PATH
## @Globals	BIN_MAIL, DEFAULT_BIN_MAIL
#----
function locate_mail() {
	testfile_clean "$BIN_MAIL" "BIN_MAIL"
	if [ -z "$BIN_MAIL" ] ; then 
		pathfind_ret "mail" "BIN_MAIL"
		if [ "$?" -ne 0 ] ; then 
			answer_with_testfile "$(gettext "Where is mail binary")" "$DEFAULT_BIN_MAIL" "BIN_MAIL"
		else 
			BIN_MAIL="$BIN_MAIL/mail"
		fi
		echo_success "$BIN_MAIL" "$ok"
	fi
	BIN_MAIL=`trim ${BIN_MAIL%/}`
	export BIN_MAIL
	log "INFO" "BIN_MAIL: $BIN_MAIL"
}

#----
## Define where is ssh binary
## find ssh in PATH
## @Globals	BIN_SSH, DEFAULT_BIN_SSH
#----
function locate_ssh() {
	testfile_clean "$BIN_SSH" "BIN_SSH"
	if [ -z "$BIN_SSH" ] ; then 
		pathfind_ret "ssh" "BIN_SSH"
		if [ "$?" -ne 0 ] ; then 
			answer_with_testfile "$(gettext "Where is ssh binary")" "$DEFAULT_BIN_SSH" "BIN_SSH"
		else 
			BIN_SSH="$BIN_SSH/ssh"
		fi
		echo_success "$BIN_SSH" "$ok"
	fi
	BIN_SSH=`trim ${BIN_SSH%/}`
	export BIN_SSH
	log "INFO" "BIN_SSH: $BIN_SSH"
}

#----
## Define where is scp binary
## find scp in PATH
## @Globals	BIN_SCP, DEFAULT_BIN_SCP
#----
function locate_scp() {
	testfile_clean "$BIN_SCP" "BIN_SCP"
	if [ -z "$BIN_SCP" ] ; then 
		pathfind_ret "scp" "BIN_SCP"
		if [ "$?" -ne 0 ] ; then 
			answer_with_testfile "$(gettext "Where is scp binary")" "$DEFAULT_BIN_SCP" "BIN_SCP"
		else 
			BIN_SCP="$BIN_SCP/scp"
		fi
		echo_success "$BIN_SCP" "$ok"
	fi
	BIN_SCP=`trim ${BIN_SCP%/}`
	export BIN_SCP
	log "INFO" "BIN_SCP: $BIN_SCP"
}

#----
## Define where is php binary
## find php, php5 in PATH
## @Globals	PHP_BIN, DEFAULT_PHP_BIN
#----
function locate_php_bin() {
	testfile_clean "$PHP_BIN" "PHP_BIN"
	if [ -z "$PHP_BIN" ] ; then
		php_binaries="php php5"
		for binary in $php_binaries ; do
			pathfind_ret "$binary" "PHP_BIN"
			if [ "$?" -eq 0 ] ; then
				PHP_BIN="$PHP_BIN/$binary"
				break
			fi
		done
		if [ -z "$PHP_BIN" ] ; then 
			answer_with_testfile "$(gettext "Where is your php binany ? ")" "$DEFAULT_PHP_BIN" "PHP_BIN"
		fi
		echo_success "$PHP_BIN" "$ok"
	fi
	PHP_BIN=`trim ${PHP_BIN%/}`
	export PHP_BIN
	log "INFO" "PHP_BIN: $PHP_BIN"
}

#----
## Define where is php-pear (PEAR.php)
## @Globals	PEAR_PATH, DEFAULT_PEAR_PATH
#----
function locate_pear() {
	testdir_clean "$PEAR_PATH" "PEAR_PATH"
	if [ -z "$PEAR_PATH" ] ; then
		answer_with_testfile "$(gettext "Where is PEAR [PEAR.php] ")" "$DEFAULT_PEAR_PATH/PEAR.php" "PEAR_PATH"
		PEAR_PATH=$(dirname $PEAR_PATH)
		echo_success "$(gettext "Path" ) $PEAR_PATH" "$ok"
	fi
	PEAR_PATH=`trim ${PEAR_PATH%/}`
	export PEAR_PATH
	log "INFO" "PEAR_PATH: $PEAR_PATH"
}

#----
## Define where is your cron.d directory
## @Globals	CRON_D, DEFAULT_CRON_D
#----
function locate_cron_d() {
	testdir_clean "$CRON_D" "CRON_D"
	if [ -z "$CRON_D" ] ; then
		if [ -d "/etc/cron.d" ] ; then
			CRON_D="/etc/cron.d"
		# Add most of init.d 
		else 
			answer_with_testdir "$(gettext "Where is your cron.d directory ?")" "$DEFAULT_CRON_D" "CRON_D"
			echo_success "Path $CRON_D" "$ok"
		fi
	fi
	CRON_D=`trim ${CRON_D%/}`
	export CRON_D
	log "INFO" "CRON_D: $CRON_D"
}

#----
## Check if variable do not have most possibility
## @param	variable to check
## @return 0	True
## @return 1	False
#----
function is_single() {
	local var="$1"

	local count=0
	for value in $var ; do
		let "count += 1"
	done

	if [ "$count" -eq 1 ] ; then
		return 0
	else 
		return 1
	fi
}

#----
## Check apache version, and configure it. Ask to restart apache server
## Make a copy of the original file as httpd.conf.initial
## <p>
## Call <@function prepare_apache_config> and <@function reload_service_apache> function
## <p>
## @param	apache config directory
## @Globals	line, DIR_APACHE_CONF, LOG_FILE, silent_install
#----
function configureApache() {
	echo -e "\n$line"
	echo -e "\t$(gettext "Configure Apache server")"
	echo -e "$line"

	local write_config="0"
	local dir_conf="$1"
	# Generate a apache config in directory
	prepare_apache_config "$dir_conf"

	if [ "$silent_install" -ne 1 ] ; then 
		if [ -e $DIR_APACHE_CONF/centreon.conf ] ; then
			echo "$(gettext "Finding Apache Centreon configuration file")"
			echo_success "'$DIR_APACHE_CONF/centreon.conf' :" "$ok"
			yes_no_default "$(gettext "Do you want to update Centreon Apache sub configuration file ?")"
      if [ "$?" -eq 0 ] ; then 
        write_config="1"
        cp -f $DIR_APACHE_CONF/centreon.conf $DIR_APACHE_CONF/centreon.conf-bak >> $LOG_FILE 2>&1
        echo_info "$(gettext "Backup Centreon Apache configuration completed")"
      fi
		else 
			yes_no_default "$(gettext "Do you want to add Centreon Apache sub configuration file ?")"
			[ "$?" -eq 0 ] && write_config="1"
		fi
	else 
		write_config="1"
    	fi
	if [ "$write_config" -eq 1 ] ; then 
		cp -f $dir_conf/centreon.apache.conf $DIR_APACHE_CONF/centreon.conf >> $LOG_FILE 2>&1
		echo_success "$(gettext "Create") '$DIR_APACHE_CONF/centreon.conf'" "$ok"
		echo_success "$(gettext "Configuring Apache")" "$ok"
		# After finishing the configuration -> 
		# reload apache ! (if admin wants :p)
		if [ "${APACHE_RELOAD:-0}" -eq 0 ] ; then 
			yes_no_default "$(gettext "Do you want to reload your Apache ?")"
			[ $? -eq 0 ] && reload_service_apache
		elif [ "${APACHE_RELOAD:-0}" -eq 1 ] ; then
			reload_service_apache
		fi
	else
		echo_info "$(gettext "Please config Apache with this example"):\n $dir_conf/centreon.apache.conf"
	fi
}

#----
## Define apache service init script and ask to reload apache
## @return 0 	Apache reload OK
## @return 1	Apache reload FAIL
#----
function reload_service_apache() {
	local service=""
	log "INFO" "$(gettext "Reloading Apache...")"
	if [ -x /etc/init.d/apache ] ; then
		service="/etc/init.d/apache"
	elif [ -x /etc/init.d/httpd ] ; then
		service="/etc/init.d/httpd"
	elif [ -x /etc/init.d/apache2 ] ; then
		service="/etc/init.d/apache2"
	elif [ -x /usr/local/etc/rc.d/apache ] ; then
		service="/usr/local/etc/rc.d/apache"
	elif [ -x /usr/local/etc/rc.d/apache2 ]; then
		service="/etc/init.d/apache2"
	else
		echo_warning "$(gettext "Unable to restart Apache server")" "$warning"
		log "WARN" "$(gettext "Unable to restart Apache server")"
	fi

	log "DEBUG" "$(gettext "use") : $service"
	# reload apache service
	$service reload >> $LOG_FILE 2>&1
	if [ "$?" -eq 0 ] ; then
		echo_success "$(gettext "Reloading Apache service")" "$ok"
		return 0
	else
		echo_failure "$(gettext "Reloading Apache service")" "$fail"
		return 1
	fi
}

#----
## Prepare a file for apache config
## This function write a config in directory ($1)
## and test if that config exist.
## @param	directory to generate apache.conf
## @return 0	create file ok
## @return 1	create file fail
#----
function prepare_apache_config() {
	local directory="$1"

	# if INSTALL_DIR_CENTREON not found, ask:
	[ -z "$INSTALL_DIR_CENTREON" ] && locate_centreon_installdir
	
	# Prepare apache config
	${CAT} << __EOT__ > $directory/centreon.apache.conf
##
## Section add by Centreon Install Setup
##
	
Alias /centreon $INSTALL_DIR_CENTREON/www/
<Directory "$INSTALL_DIR_CENTREON/www">
    Options Indexes
    AllowOverride AuthConfig Options
    Order allow,deny
    Allow from all
</Directory>

__EOT__

	if [ -e $directory/centreon.apache.conf ] ; then 
		return 0
	else 
		log "INFO" "$(gettext "Problem when I generate an apache configuration")"
		return 1
	fi
}

#----
## Prepare Sudo config file
## This function write a config in directory ($1)
## <p>
## Call:<p>
##	- <@function locate_sudo><p>
##	- <@function check_nagios_init_script>
## @param	directory to generate a centreon.sudo file
## @return 0	create file ok
## @return 1	create file fail
## @Globals	NAGIOS_BINARY, INIT_D, WEB_USER, NAGIOS_INIT_SCRIPT
#----
function prepare_sudo_config() {
	local directory="$1"

    	locate_sudo
	# Find Nagios Init Script
	check_nagios_init_script
	# find nagios binary if not define
	[ -z "$NAGIOS_BINARY" ] && locate_nagios_binary
	[ -z "$INIT_D" ] && locate_init_d
	# Prepare sudo.conf
	
	${CAT} <<- __EOT__ > $directory/centreon.sudo
	## BEGIN: CENTREON SUDO
	#Add by CENTREON installation script
	User_Alias      CENTREON=$WEB_USER,$NAGIOS_USER
	Defaults:CENTREON !requiretty
	# Nagios Restart
	CENTREON   ALL = NOPASSWD: $NAGIOS_INIT_SCRIPT* restart
	CENTREON   ALL = NOPASSWD: $NAGIOS_INIT_SCRIPT restart
	# Nagios reload
	CENTREON   ALL = NOPASSWD: $NAGIOS_INIT_SCRIPT* reload
	CENTREON   ALL = NOPASSWD: $NAGIOS_INIT_SCRIPT reload
	# Nagios test config
	CENTREON   ALL = NOPASSWD: $NAGIOS_BINARY* -v *
	CENTREON   ALL = NOPASSWD: $NAGIOS_BINARY -v *
	# Nagios test for optim config
	CENTREON   ALL = NOPASSWD: $NAGIOS_BINARY* -s *
	CENTREON   ALL = NOPASSWD: $NAGIOS_BINARY -s *
	# Snmptrapd Restart
	CENTREON   ALL = NOPASSWD: $INIT_D/snmptrapd restart
	# CentStorage Restart
	CENTREON   ALL = NOPASSWD: $INIT_D/centstorage restart
	# CentStorage stop
	CENTREON   ALL = NOPASSWD: $INIT_D/centstorage stop
	# CentStorage start
	CENTREON   ALL = NOPASSWD: $INIT_D/centstorage start
	## END: CENTREON SUDO 

	__EOT__


	if [ -e $directory/centreon.sudo ] ; then 
		return 0
	else 
		log "INFO" "$(gettext "Problem when I generate a sudo configuration")"
		return 1
	fi
}

#----
## Find config problem on sudo
## If I found a problem, print a warning and need to press enter.
## @Globals	LOG_FILE
## @return 0	no problem in sudo file
## @return 1	possible problem in sudo file
#----
function is_suspect_conf_sudo() {
	local sudo_file="$1"
	${GREP} -e "^Defaults.*requiretty$" $sudo_file >> $LOG_FILE 2>&1
	if [ "$?" -eq 0 ] ; then
		echo_warning "$(gettext "I think you'll have a problem with\n'Default requiretty' in sudo file")"
		echo -e "$(gettext "Press enter to continue.")"
		read
		return 1
	fi
	return 0
}

#----
## Configure Sudo on system 
## Need a directory to store a config 
## Call <@function prepare_sudo_config>
## @param	Directory to store a Sudo config (generate)
## @Globals	SUDO_FILE, line
## @return 0	end
#----
function configureSUDO(){
	echo -e "\n$line"
	echo -e "\t$(gettext "Configure Sudo")"
	echo -e "$line"
    	local no_force_sudo="0"
	local dir_conf="$1"
	# Generate a sudo config in directory
	prepare_sudo_config "$dir_conf"

	# Try to detect old configuration
	sudo=`${GREP} -e "[CO][ER][NE][TO][RN]" $SUDO_FILE > /dev/null 2>&1 ; echo $?`
	if [ $sudo -eq 1 ]; then
    		echo_info "$(gettext "Your sudo is not configured")"
		
		if [ "${FORCE_SUDO_CONF:-0}" -eq 1 ] ; then
			no_force_sudo="0"
		else
			yes_no_default "$(gettext "Do you want me to configure your sudo ? (WARNING) ")"
			no_force_sudo="$?"
		fi
		if [ $no_force_sudo -eq 0 ] ; then 
			${CAT} $dir_conf/centreon.sudo >> $SUDO_FILE
			echo_success "$(gettext "Configuring Sudo")" "$ok"
		else
			echo_passed "$(gettext "Please configure your sudo with this example"):\n\t $dir_conf/centreon.sudo" "$passed"
		fi
	else
		#echo_passed "$(gettext "Sudo is already configured")" "$passed"
		## ticket #7 (upgrade script here)
		echo_info "$(gettext "Your sudo has been configured previously")"
		if [ "${FORCE_SUDO_CONF:-0}" -eq 1 ] ; then
			no_force_sudo="0"
		else
			yes_no_default "$(gettext "Do you want me to reconfigure your sudo ? (WARNING) ")"
			no_force_sudo="$?"
		fi
		if [ $no_force_sudo -eq 0 ] ; then 
			clean_sudo $SUDO_FILE 0
			${CAT} $dir_conf/centreon.sudo >> $SUDO_FILE
			echo_success "$(gettext "Configuring Sudo")" "$ok"
		else
			echo_passed "$(gettext "Please configure your sudo with this example"):\n\t $dir_conf/centreon.sudo" "$passed"
		fi
	fi
	log "INFO" "$(gettext "Please configure your sudo with this example"): $dir_conf/centreon.sudo"
	# Add a simple test for Defaults Requiretty problem on CentOS, Fedora...
	#is_suspect_conf_sudo $SUDO_FILE
	#if [ "$?" -eq 1 ] ; then
	#	echo_warning "$(gettext "For security policy, your sudo's\nconfiguration would only run when the user is logged into a real tty. Please adjust your configuration by commenting 'Defaults requiretty' line in your configuration file.")" "$warning"
	#fi
	return 0
}

#----
## Create a config file for Web post install
## @Globals	line, INSTALL_DIR_CENTREON, CENTREON_ETC, INSTALL_DIR_NAGIOS,
## @Globals	NAGIOS_ETC, NAGIOS_PLUGIN, NAGIOS_BINARY, NAGIOSTATS_BINARY, 
## @Globals	NAGIOS_INIT_SCRIPT, BIN_RRDTOOL, WEB_USER, WEB_GROUP, 
## @Globals	NAGIOS_USER, NAGIOS_GROUP, BIN_MAIL, BIN_MAIL
#----
function createConfFile()
{
	echo -e "\n$line"
	echo -e "\t\t$(gettext "Centreon Post Install")"
	echo -e "$line"

	INSTALL_DIR_CENTREON_CONF="$INSTALL_DIR_CENTREON/www/install/install.conf.php"
	# Reinit file if exist	
	touch $INSTALL_DIR_CENTREON_CONF
	${CAT} << __EOT__ > $INSTALL_DIR_CENTREON_CONF
<?php
/* 
 * Centreon is developped with GPL Licence 2.0 : 
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt 
 * Developped by : Julien Mathis - Romain Le Merlus  
 *  
 * The Software is provided to you AS IS and WITH ALL FAULTS. 
 * Centreon makes no representation and gives no warranty whatsoever, 
 * whether express or implied, and without limitation, with regard to the quality, 
 * any particular or intended purpose of the Software found on the Centreon web site. 
 * In no event will Centreon be liable for any direct, indirect, punitive, special, 
 * incidental or consequential damages however they may arise and even if Centreon has 
 * been previously advised of the possibility of such damages. 
 *  
 * For information : contact@centreon.com 
 */

\$conf_centreon['centreon_dir'] = "$INSTALL_DIR_CENTREON/";
\$conf_centreon['centreon_etc'] = "$CENTREON_ETC/";
\$conf_centreon['centreon_dir_www'] = "$INSTALL_DIR_CENTREON/www/";
\$conf_centreon['centreon_dir_rrd'] = "$INSTALL_DIR_CENTREON/rrd/";
\$conf_centreon['nagios'] = "$INSTALL_DIR_NAGIOS/";
\$conf_centreon['nagios_conf'] = "$NAGIOS_ETC/";
\$conf_centreon['nagios_plugins'] = "$NAGIOS_PLUGIN/";
\$conf_centreon['nagios_binary'] = "$NAGIOS_BINARY";
\$conf_centreon['nagiostats_binary'] = "$NAGIOSTATS_BINARY";
\$conf_centreon['nagios_init_script'] = "$NAGIOS_INIT_SCRIPT";
\$conf_centreon['rrdtool_dir'] = "$BIN_RRDTOOL";
\$conf_centreon['apache_user'] = "$WEB_USER";
\$conf_centreon['apache_group'] = "$WEB_GROUP";
\$conf_centreon['nagios_user'] = "$NAGIOS_USER";
\$conf_centreon['nagios_group'] = "$NAGIOS_GROUP";
\$conf_centreon['mail'] = "$BIN_MAIL";
\$conf_centreon['pear_dir'] = "$PEAR_PATH";

__EOT__

	# Conf nagios.cfg
	
	for fichier in `${CAT} $NAGIOS_ETC/nagios.cfg | ${GREP} "_file" | ${GREP} -v "\#"`
	do
		echo "\$conf_centreon['$(echo "$fichier" |cut -d= -f1)'] = \"$(echo "$fichier" |cut -d= -f2)\";" >> $INSTALL_DIR_CENTREON_CONF
	done
	
	# Conf nagios.cfg
	
	for fichier in `${CAT} $NAGIOS_ETC/nagios.cfg | ${GREP} "_path" | ${GREP} -v "\#"`
	do
		echo "\$conf_centreon['$(echo "$fichier" |cut -d= -f1)'] = \"$(echo "$fichier" |cut -d= -f2)\";" >> $INSTALL_DIR_CENTREON_CONF
	done
	
	# Conf GCI.cfg
	
	for fichier in `${CAT} $NAGIOS_ETC/cgi.cfg | ${GREP} "physical_html_path" | ${GREP} -v "\#"`
	do
		echo "\$conf_centreon['$(echo "$fichier" |cut -d= -f1)'] = \"$(echo "$fichier" |cut -d= -f2)\";" >> $INSTALL_DIR_CENTREON_CONF		
	done
	
	echo "?>" >> $INSTALL_DIR_CENTREON_CONF
	log "INFO" "$(gettext "Change right on") : $INSTALL_DIR_CENTREON_CONF"
	${CHOWN} $WEB_USER:$WEB_GROUP $INSTALL_DIR_CENTREON_CONF >> $LOG_FILE 2>&1
	echo_success "Create $INSTALL_DIR_CENTREON_CONF" "OK"
	
}

#----
## Create a config file for CentWeb
## Create a config file with all used variables.
## This file will use in upgrade progess.
## @Globals	CENTREON_ETC, INSTALL_DIR_CENTREON, INSTALL_DIR_NAGIOS,
## @Globals	NAGIOS_ETC, NAGIOS_USER, INIT_D, DIR_APACHE, NAGIOS_P1_FILE
## @Globals	NAGIOS_PLUGIN, NAGIOS_IMG, NAGIOS_BINARY, NAGIOSTATS_BINARY,
## @Globals	NAGIOS_VAR, RRD_PERL, SUDO_FILE, WEB_USER, WEB_GROUP,
## @Globals	NAGIOS_GROUP, BIN_RRDTOOL, BIN_MAIL, PEAR_PATH, CENTREON_LOG,
## @Globals	CENTREON_ETC, CENTREON_GENDIR, CRON_D, NDOMOD_BINARY
#----
function createCentreonInstallConf() {
	${CAT} <<- __EOT__ > $CENTREON_ETC/instCentWeb.conf
	INSTALL_DIR_CENTREON=$INSTALL_DIR_CENTREON
	INSTALL_DIR_NAGIOS=$INSTALL_DIR_NAGIOS
	NAGIOS_ETC=$NAGIOS_ETC
	NAGIOS_PLUGIN=$NAGIOS_PLUGIN
	NAGIOS_IMG=$NAGIOS_IMG
	NAGIOS_BINARY=$NAGIOS_BINARY
	NAGIOSTATS_BINARY=$NAGIOSTATS_BINARY
	NAGIOS_VAR=$NAGIOS_VAR
	RRD_PERL=$RRD_PERL
	SUDO_FILE=$SUDO_FILE
	WEB_USER=$WEB_USER
	WEB_GROUP=$WEB_GROUP
	NAGIOS_USER=$NAGIOS_USER
	NAGIOS_GROUP=$NAGIOS_GROUP
	BIN_RRDTOOL=$BIN_RRDTOOL
	BIN_MAIL=$BIN_MAIL
	PEAR_PATH=$PEAR_PATH
	CENTREON_LOG=$CENTREON_LOG
	CENTREON_ETC=$CENTREON_ETC
	CENTREON_GENDIR=$CENTREON_GENDIR
	CENTREON_VARLIB=$CENTREON_VARLIB	
	CRON_D=$CRON_D
	INIT_D=$INIT_D
	PHP_BIN=$PHP_BIN
	DIR_APACHE=$DIR_APACHE
	DIR_APACHE_CONF=$DIR_APACHE_CONF
	CENTPLUGINSTRAPS_BINDIR=$CENTPLUGINSTRAPS_BINDIR
	__EOT__

	[ -n "$NAGIOS_P1_FILE" ] && \
		echo "NAGIOS_P1_FILE=$NAGIOS_P1_FILE" >> $CENTREON_ETC/instCentWeb.conf

	[ -n "$NDOMOD_BINARY" ] && \
		echo "NDOMOD_BINARY=$NDOMOD_BINARY" >> $CENTREON_ETC/instCentWeb.conf

	echo_success "Create $CENTREON_ETC/instCentWeb.conf " "OK"
	return 0
}

#---
## Create a config file for CentStorage
## This file will use for upgrade process
## @Globals	CENTREON_ETC, INSTALL_DIR_CENTREON, CENTREON_LOG, CENTREON_ETC
## @Globals	CENTREON_RUNDIR, CENTSTORAGE_RRD, CENTSTORAGE_BINDIR
## @Globals	NAGIOS_USER, NAGIOS_GROUP, RRD_PERL, CRON_D, INIT_D
#----
function createCentStorageInstallConf() {
	${CAT} <<- __EOT__ > $CENTREON_ETC/instCentStorage.conf
	INSTALL_DIR_CENTREON=$INSTALL_DIR_CENTREON
	CENTREON_LOG=$CENTREON_LOG
	CENTREON_ETC=$CENTREON_ETC
	CENTREON_RUNDIR=$CENTREON_RUNDIR
	CENTREON_GENDIR=$CENTREON_GENDIR
	CENTREON_VARLIB=$CENTREON_VARLIB
	RRD_PERL=$RRD_PERL
	NAGIOS_VAR=$NAGIOS_VAR
	INIT_D=$INIT_D
	CRON_D=$CRON_D
	CENTSTORAGE_BINDIR=$CENTSTORAGE_BINDIR
	CENTSTORAGE_RRD=$CENTSTORAGE_RRD
	NAGIOS_USER=$NAGIOS_USER
	NAGIOS_GROUP=$NAGIOS_GROUP
	__EOT__

	echo_success "Create $CENTREON_ETC/instCentStorage.conf " "OK"
	return 0
}

#---
## Create a config file for CentCore
## This file will use for upgrade process
## @Globals	CENTREON_ETC, INSTALL_DIR_CENTREON, CENTREON_LOG, CENTREON_ETC
## @Globals	CENTREON_RUNDIR, CENTSTORAGE_RRD, CENTSTORAGE_BINDIR
## @Globals	NAGIOS_USER, NAGIOS_GROUP, RRD_PERL, CRON_D, INIT_D
#----
function createCentCoreInstallConf() {
	${CAT} <<- __EOT__ > $CENTREON_ETC/instCentCore.conf
	INSTALL_DIR_CENTREON=$INSTALL_DIR_CENTREON
	CENTREON_ETC=$CENTREON_ETC
	CENTREON_RUNDIR=$CENTREON_RUNDIR
	CENTREON_LOG=$CENTREON_LOG
	CENTREON_VARLIB=$CENTREON_VARLIB
	CENTREON_GENDIR=$CENTREON_GENDIR
	CENTCORE_BINDIR=$CENTCORE_BINDIR
	BIN_SSH=$BIN_SSH
	BIN_SCP=$BIN_SCP
	NAGIOS_ETC=$NAGIOS_ETC
	NAGIOS_GROUP=$NAGIOS_GROUP
	NAGIOS_USER=$NAGIOS_USER
	RRD_PERL=$RRD_PERL
	INIT_D=$INIT_D
	__EOT__

	echo_success "Create $CENTREON_ETC/instCentCore.conf " "OK"
	return 0
}

#---
## Create a config file for CentPlugins
## This file will use for upgrade process
## @Globals	CENTREON_ETC, NAGIOS_PLUGIN, INSTALL_DIR_NAGIOS, NAGIOS_ETC
## @Globals	RRD_PERL, CENTPLUGINS_TMP, NAGIOS_USER, NAGIOS_GROUP, INIT_D
## @Globals	SNMP_ETC, SNMPTT_BINDIR, CENTPLUGINSTRAPS_BINDIR, WEB_USER
#----
function createCentPluginsInstallConf() {
	${CAT} <<- __EOT__ > $CENTREON_ETC/instCentPlugins.conf
	# Use in CentPlugins.sh
	NAGIOS_PLUGIN=$NAGIOS_PLUGIN
	INSTALL_DIR_NAGIOS=$INSTALL_DIR_NAGIOS
	NAGIOS_ETC=$NAGIOS_ETC
	RRD_PERL=$RRD_PERL
	CENTPLUGINS_TMP=$CENTPLUGINS_TMP
	NAGIOS_USER=$NAGIOS_USER
	NAGIOS_GROUP=$NAGIOS_GROUP
	INIT_D=$INIT_D
	__EOT__

	if [ "$PROCESS_CENTREON_SNMP_TRAPS" -eq 1 ] ; then
	${CAT} <<- __EOT__ >>  $CENTREON_ETC/instCentPlugins.conf
	# Use in CentPluginsTraps.sh
	CENTREON_ETC=$CENTREON_ETC
	SNMP_ETC=$SNMP_ETC
	SNMPTT_BINDIR=$SNMPTT_BINDIR
	CENTPLUGINSTRAPS_BINDIR=$CENTPLUGINSTRAPS_BINDIR
	WEB_USER=$WEB_USER
	__EOT__
	fi

	echo_success "Create $CENTREON_ETC/instCentPlugins.conf " "OK"
	return 0
}

#----
## Find the user nagios in nagios.cfg and ask if we do not find
## @return 0
## @Globals	NAGIOS_ETC, NAGIOS_USER
#----
function find_user_nagios()
{
	# If I am on this function, I suppose you do not force a nagios user name. So I init this :p
	NAGIOS_USER=""
	# In a first time, I search on nagios.cfg because it had most of chance to find it.
	if [ -f $NAGIOS_ETC/nagios.cfg ] ; then 
		NAGIOS_USER=`${GREP} "^nagios_user" $NAGIOS_ETC/nagios.cfg | cut -d= -f2 2>/dev/null`
	fi

	# If I not locate nagios user, I find on all file.
	if [ -z "$NAGIOS_USER" ] ; then
		local NAGIOS_USER_TEMP=""
		log "INFO" "$(gettext "Find nagios user in all file in") : $NAGIOS_ETC"
		for fichier in $NAGIOS_ETC/*.cfg ; do
			if [ -f "$fichier" ] ; then
			NAGIOS_USER_TEMP=`${GREP} "^nagios_user" $fichier | cut -d= -f2 2>/dev/null`
				if [ -n "$NAGIOS_USER_TEMP" ] ; then
					NAGIOS_USER="$NAGIOS_USER_TEMP"
				fi
			fi
		done
	fi
    
	if [ -z "$NAGIOS_USER"  ] ; then
		log "INFO" "$(gettext "First find nagios user fail")"
		return 1	
    	else
		is_single "$NAGIOS_USER"
		if [ "$?" -eq 1 ] ; then
			echo -e "$(gettext "Please select a good nagios user")"
			select_in_array "NAGIOS_USER" "${NAGIOS_USER[@]}"
		fi
		echo_info "$(gettext "Finding Nagios user") :" "$NAGIOS_USER"
	fi
	return 0
}

#----
## Find the group nagios in nagios.cfg and ask if we do not find
## @return 0
## @Globals	NAGIOS_ETC, NAGIOS_GROUP
#----
function find_group_nagios()
{
	# Same to user, If I am on this function I must reset NAGIOS_GROUP
	NAGIOS_GROUP=""
	# In a first time, I search on nagios.cfg because it had most of chance to find it.
	if [ -f $NAGIOS_ETC/nagios.cfg ] ; then  
		NAGIOS_GROUP=`${GREP} "^nagios_group" $NAGIOS_ETC/nagios.cfg | cut -d= -f2 2>/dev/null`
	fi

	# If I not locate nagios group, I find on all file.
	if [ -z "$NAGIOS_GROUP"  ] ; then
	local NAGIOS_GROUP_TEMP=""
		log "INFO" "$(gettext "Find nagios group in all file in") : $NAGIOS_ETC"
		for fichier in $NAGIOS_ETC/*.cfg ; do
			if [ -f "$fichier" ];	then
				NAGIOS_GROUP_TEMP=`${GREP} "^nagios_group" $fichier | cut -d= -f2 2>/dev/null`
				if [ -n "$NAGIOS_GROUP_TEMP" ]; then
					NAGIOS_GROUP="$NAGIOS_GROUP_TEMP"
				fi
			fi
		done
	fi
    
	if [ -z "$NAGIOS_GROUP"  ] ; then
		log "INFO" "$(gettext "First find nagios user fail")"
		return 1
	else 
		is_single "$NAGIOS_GROUP"
		if [ "$?" -eq 1 ] ; then
			echo -e "$(gettext "Please select a good nagios group")"
			select_in_array "NAGIOS_GROUP" "${NAGIOS_GROUP[@]}"
		fi
		echo_info "$(gettext "Finding Nagios group") :" "$NAGIOS_GROUP"	
    	fi
	return 0
}

#----
## Check the user nagios
## if NAGIOS_USER already define, this functions test if is it a valid system user
## @return 0	found
## @Globals	NAGIOS_USER
#----
function check_user_nagios()
{
	local RC="1"        

	# check if you want to force nagios user
	FORCE_NAGIOS_USER=${FORCE_NAGIOS_USER:-0}

	if [ -n "$NAGIOS_USER" ] ; then
		if [ "$FORCE_NAGIOS_USER" -eq 0 ] ; then 
			log "DEBUG" "$(gettext "Test user nagios")"
			id -u "$NAGIOS_USER" >> $LOG_FILE 2>&1
			RC="$?"
		else 
			RC=0
		fi
		if [ "$RC" -eq 0 ] ; then
			echo_info "$(gettext "Finding Nagios user") :" "$NAGIOS_USER"
			return 0
		fi
	fi
    	# Try to find nagios user/group from nagios.cfg file.
	# If not, we ask...
	find_user_nagios

	if [ "$?" -eq 0 ] ; then 
            # put nagios user into apache group
            usermod -aG $WEB_GROUP $NAGIOS_USER	
            return 0
	fi

	echo_failure "$(gettext "Nagios User not found")" "$fail"
	echo -e "$(gettext "Have you create you nagios user ? use this command")"
	echo -e "useradd -G $NAGIOS_GROUP $NAGIOS_USER \n"
	echo -e "$(gettext "If you want to force a nagios user name, use (FORCE_)NAGIOS_USER variable(s) in a template file and try 'bash install.sh -f file'")"
	clean_and_exit 1
	
}

#----
## Check the nagios group
## Find un /etc/group if is a valid group.
## @Globals	NAGIOS_GROUP
#----
function check_group_nagios()
{
	local RC="1"
	# check if you want to force nagios group
	FORCE_NAGIOS_GROUP=${FORCE_NAGIOS_GROUP:-0}

	if [ -n "$NAGIOS_GROUP" ] ; then
		if [ "$FORCE_NAGIOS_GROUP" -eq 0 ] ; then 
			log "DEBUG" "$(gettext "Test group nagios")"
			${GREP} "$NAGIOS_GROUP" /etc/group >> $LOG_FILE 2>&1
			RC="$?"
		else
			RC=0
		fi
		if [ "$RC" -eq 0 ] ; then
			echo_info "$(gettext "Finding Nagios group") :" "$NAGIOS_GROUP"
			return 0
		fi
	fi
	# Try to find nagios user/group from nagios.cfg file.
	# If not, we ask...
	find_group_nagios

	if [ "$?" -eq 0 ] ; then 
		return 0
	fi

	echo_failure "$(gettext "Nagios Group not found")" "$fail"
	echo -e "$(gettext "Have you create you nagios group ? use this command")"
	echo -e "groupadd $NAGIOS_GROUP \n"
	echo -e "$(gettext "If you want to force a nagios group name, use (FORCE_)NAGIOS_GROUP variable(s) in a template file and try 'bash install.sh -f file'")"
	clean_and_exit 1
}

#----
## Define where is a nagios init script
## Find in list of chose and request if not found
## @Globals	NAGIOS_INIT_SCRIPT, DEFAULT_NAGIOS_INIT_SCRIPT, INIT_D
#----
function check_nagios_init_script()
{
	# Try to find nagios init script.
	# It's possible to force that variable.
	if [ -n "$NAGIOS_INIT_SCRIPT" -a -x "$NAGIOS_INIT_SCRIPT" ] ; then
		log "INFO" "$(gettext "Use default variable") : $NAGIOS_INIT_SCRIPT"
	elif [ -x "$INIT_D/nagios" ]; then
		NAGIOS_INIT_SCRIPT="/etc/init.d/nagios"
	elif [ -x "$INIT_D/nagios2" ] ; then
		NAGIOS_INIT_SCRIPT="/etc/init.d/nagios2"
	elif [ -x "$INIT_D/nagios3" ] ; then
		NAGIOS_INIT_SCRIPT="/etc/init.d/nagios3"
	elif [ -x "/usr/local/etc/rc.d/nagios" ] ; then
		NAGIOS_INIT_SCRIPT="/usr/local/etc/rc.d/nagios"
	elif [ -x "$DEFAULT_NAGIOS_INIT_SCRIPT" ] ; then
		NAGIOS_INIT_SCRIPT=$DEFAULT_NAGIOS_INIT_SCRIPT
	else
    		echo_passed "$(gettext "Not possible to find Nagios init script")" "$critical"
		answer_with_testfile "$(gettext "Where is Nagios init script")" "NO_DEFAULT" "NAGIOS_INIT_SCRIPT"
	fi
	NAGIOS_INIT_SCRIPT=${NAGIOS_INIT_SCRIPT%/}
	echo_success "Nagios init script " "$ok"
}

#----
## Define where is Apache config directory
## @return 0
## @Globals	DIR_APACHE, DIR_APACHE_CONF, APACHE_CONF
#----
function check_httpd_directory()
{
	if [ -z "$DIR_APACHE" -o -z "$DIR_APACHE_CONF" ] ; then 
		if [ -d /etc/apache/conf ]; then
			DIR_APACHE="/etc/apache/conf"
			DIR_APACHE_CONF="/etc/apache/conf.d"
		elif [ -d /usr/local/apache2/conf ] ; then
			DIR_APACHE="/usr/local/apache2/conf"
			DIR_APACHE_CONF="/usr/local/apache2/conf"
		elif [ -d /etc/apache2 ] ; then
			DIR_APACHE="/etc/apache2"			
			DIR_APACHE_CONF="/etc/apache2/conf.d"
			if [ ! -d "$DIR_APACHE_CONF" ] ; then
				mkdir "$DIR_APACHE_CONF"
				echo_success "$(gettext "Created Apache configuration directory")" "$ok"
			fi
		elif [ -d /etc/httpd/conf ] ; then
			DIR_APACHE="/etc/httpd/conf"
			DIR_APACHE_CONF="/etc/httpd/conf.d"
		elif [ -d /usr/local/etc/apache ] ; then
			DIR_APACHE="/usr/local/etc/apache"
			DIR_APACHE_CONF="/usr/local/etc/apache/Includes"
		elif [ -d /usr/local/etc/apache2 ] ; then
			DIR_APACHE="/usr/local/etc/apache2"
			DIR_APACHE_CONF="/usr/local/etc/apache2/Includes"
		elif [ -d /usr/local/etc/apache22 ] ; then
			# add for freeBSD 7 with apache2.2
			DIR_APACHE="/usr/local/etc/apache22"
			DIR_APACHE_CONF="/usr/local/etc/apache22/Includes"
		else 
			echo_passed "$(gettext "Apache config directoty not found")" "$critical"
			answer_with_testdir "$(gettext "Where is your Apache etc directory")" "NO_DEFAULT" "DIR_APACHE"
			answer_with_testdir "$(gettext "Where is your Apache conf.d directory")" "NO_DEFAULT" "DIR_APACHE_CONF"
		fi
	fi
	DIR_APACHE=${DIR_APACHE%/}
	export DIR_APACHE
	DIR_APACHE_CONF=${DIR_APACHE_CONF%/}
	export DIR_APACHE_CONF
	log "INFO" "DIR_APACHE: $DIR_APACHE"
	log "INFO" "DIR_APACHE_CONF: $DIR_APACHE_CONF"

	if [ -z "$APACHE_CONF" ] ; then 
		if [ -e $DIR_APACHE/apache2.conf ] ; then
			APACHE_CONF="apache2.conf"
		elif [ -e $DIR_APACHE/apache.conf ] ; then
			APACHE_CONF="apache.conf"
		elif [ -e $DIR_APACHE/commondhttpd.conf ] ; then
			APACHE_CONF="commondhttpd.conf"
		elif [ -e $DIR_APACHE/httpd.conf ] ; then
			APACHE_CONF="httpd.conf"
		else
			echo_passed "$(gettext "Apache config file not found")" "$critical"
			answer_with_testfile "$(gettext "Where is your Apache config file")" "NO_DEFAULT" "APACHE_CONF"
		fi
	fi
	APACHE_CONF=${APACHE_CONF%/}
	export APACHE_CONF
	log "INFO" "APACHE_CONF: $APACHE_CONF"
	return 0
}

#----
## Find Apache user
## @Globals	WEB_USER, DIR_APACHE, APACHE_CONF
#----
function check_user_apache()
{
	# init WEB_USER if not define
	WEB_USER="$WEB_USER"

	if [ -n "$WEB_USER" ] ; then 
		echo_info "$(gettext "Finding Apache user") :" "$WEB_USER"
		return 0
	fi
	local found=0
	if [ -e /etc/apache2/envvars ] ; then 
		log "INFO" "$(gettext "Use envvars file for apache user")"
		# for Debian system (lenny)
		WEB_USER=`${CAT} /etc/apache2/envvars |${GREP} "USER" | cut -d= -f2`
		if [ -z "$WEB_USER" ] ; then 
			found=0
		else 
			found=1
		fi
	elif [ -e /etc/apache2/uid.conf ] ; then
		log "INFO" "$(gettext "Use uid.conf file for apache user")"
		# for SuSe system
		WEB_USER=`${CAT} /etc/apache2/uid.conf |${GREP} -e "^User" | cut -d" " -f2`
		if [ -z "$WEB_USER" ] ; then 
			found=0
		else 
			found=1
		fi
	fi 
	if [ "$found" -eq 0 ] ; then 
		WEB_USER=`${CAT} $DIR_APACHE/$APACHE_CONF | ${GREP} -e "^User" | cut -d" " -f2`
		if [ -z "$WEB_USER"  ] ; then
			local WEB_USER_TEMP=""
			for fichier in $DIR_APACHE/*
			do
				if [ -f "$fichier" ] ; then
					log "INFO" "$(gettext "check apache user in") : $fichier"
					WEB_USER_TEMP=`${CAT} $fichier | ${GREP} -e "^User" | cut -d" " -f2`
					if [ -n "$WEB_USER_TEMP" ] ; then
						log "INFO" "$(gettext "found apache user in") : $fichier"
						WEB_USER=$WEB_USER_TEMP
					fi
				fi
			done
		fi
	fi
	echo_info "$(gettext "Finding Apache user") :" "$WEB_USER"
	return 0
}

#----
## Find Apache group
## @Globals	WEB_GROUP, DIR_APACHE, APACHE_CONF
#----
function check_group_apache()
{
	# init WEB_GROUP if not define
	WEB_GROUP="$WEB_GROUP"

	if [ -n "$WEB_GROUP" ] ; then 
		echo_info "$(gettext "Finding Apache group") :" "$WEB_GROUP"
		return 0
	fi
	local found=0
	if [ -e /etc/apache2/envvars ] ; then
		# for debian system
		WEB_GROUP=`${CAT} /etc/apache2/envvars |${GREP} "GROUP" |cut -d= -f2`
		if [ -z "$WEB_GROUP" ] ; then 
			found=0
		else 
			found=1
		fi
	elif [ -e /etc/apache2/uid.conf ] ; then
		# for SuSe system
		WEB_GROUP=`${CAT} /etc/apache2/uid.conf |${GREP} -e "^Group" | cut -d" " -f2`
		if [ -z "$WEB_GROUP" ] ; then 
			found=0
		else 
			found=1
		fi
	fi
	if [ "$found" -eq 0 ] ; then 
		WEB_GROUP=`${CAT} $DIR_APACHE/$APACHE_CONF | ${GREP} -e "^Group" | cut -d" " -f2`
		if [  -z "$WEB_GROUP"  ] ; then
			local WEB_GROUP_TMP=""
			for fichier in $DIR_APACHE/*
			do
				if [ -f "$fichier" ];	then
					WEB_GROUP_TEMP=`${CAT} $fichier | ${GREP} -e "^Group" | cut -d" " -f2`
					if [ -n "$WEB_GROUP_TEMP" ]; then
						WEB_GROUP=$WEB_GROUP_TEMP
					fi
				fi
			done
		fi
	fi
	echo_info "$(gettext "Finding Apache group") :" "$WEB_GROUP"
	return 0
}


#----
## Copy Source directory on temporary working directory
## Copy Source directory and prepare work and final
## @Globals	TMP_DIR
#----
function copyInTempFile()
{
	local srclistcp="bin cron doc GPL_LIB lib snmptrapd snmptt www plugins libinstall"
	# Prepare centreon Plugins
	echo "$(gettext "Preparing Centreon temporary files")"
	if [ -d $TMP_DIR ] ; then
		echo_passed "$TMP_DIR $(gettext "exists, it will be moved...")"
		mv $TMP_DIR $TMP_DIR.`date +%Y%m%d-%k%m%S`
	fi
	mkdir -p $TMP_DIR/src
	mkdir -p $TMP_DIR/work
	mkdir -p $TMP_DIR/final

	for folder in $srclistcp ; do
		log "INFO" "$(gettext "Copy") $BASE_DIR/$folder $TMP_DIR/src/"
		cp -Rf $BASE_DIR/$folder $TMP_DIR/src/ 
	done
}	

#----
## use php script to check pear module
## @param	list of pear modules
## @return	return code of php script
## @Globals	PHP_BIN, INSTALL_DIR
#----
function check_pear_module() {
	local module_list=$1
	echo -e "$(gettext "Check PEAR modules")"
	$PHP_BIN $INSTALL_DIR/check_pear.php check $module_list
	return "$?"
}

#----
## use php script to install missed pear module
## @param	list of pear modules
## @return	return code of php script
## @Globals	PHP_BIN, INSTALL_DIR
#----
function install_pear_module() {
	local module_list=$1
	echo -e "$(gettext "Installing PEAR modules")"
	$PHP_BIN $INSTALL_DIR/check_pear.php install $module_list
	return "$?"
}

#----
## use php script to upgrade pear module
## @param	list of pear modules
## @return	return code of php script
## @Globals	PHP_BIN, INSTALL_DIR
#----
function upgrade_pear_module() {
	local module_list=$1
	echo -e "$(gettext "Upgrading PEAR modules")"
	$PHP_BIN $INSTALL_DIR/check_pear.php upgrade $module_list
	return "$?"
}

#----
## install init script on distrib
## use this fonction to install a init script on your system
## it call <@function find_OS> to define install command
## @param	name of service
## @return 0	install service ok
## @return 1	install service fail
#----
function install_init_service() {
	# how to find methode to install in rc.d directory a correct link ?
	# debian	update-rc.d
	# redhat	chkconfig
	# Suse		chkconfig
	# FreeBSD	add ${service}_enable=YES in /etc/rc.conf
	local service=$1
	OS=""
	find_OS "OS"
	if [ "$OS" = "DEBIAN" ] ; then
		update-rc.d $service start 40 2 3 4 5 . stop 30 0 1 6 .
	elif [ "$OS" = "SUSE" ] ; then
		chkconfig --add $service
	elif [ "$OS" = "REDHAT" ] ; then
    # Just for CentOS :p bug #1148
    if [ -x /sbin/chkconfig ] ; then
      /sbin/chkconfig --add $service
    else
		 chkconfig --add $service
   fi
	elif [ "$OS" = "FREEBSD" ] ; then
		echo_info "$(gettext "You must configure your /etc/rc.conf with"): ${service}_enable=YES"
	else
		echo_passed "$(gettext "Impossible to install your run level for ") $service" "$fail"
		return 1
	fi
	return 0
} 

#----
## Define OS
## check on etc to find a specific file <p>
## Debian, Suse, Redhat, FreeBSD
## @param	variable to set a result
## @return 0	OS found
## @return 1	OS not found
#----
function find_OS() {
	local distrib=$1
	local dist_found=""
	local system=""
	local lsb_release=""
	system="$(uname -s)"
	if [ "$system" = "Linux" ] ; then
		if [ "$(pathfind lsb_release; echo $?)" -eq "0" ] ; then
			lsb_release="$(lsb_release -i -s)"
		else
			lsb_release="NOT_FOUND"
		fi
		if [ "$lsb_release" = "Debian" ] || \
			[ "$lsb_release" = "Ubuntu" ] || \
			[ -e "/etc/debian_version" ] ; then 
			dist_found="DEBIAN"
			log "INFO" "$(gettext "GNU/Linux Debian Distribution")"
		elif [ "$lsb_release" = "SUSE LINUX" ] || \
			[ -e "/etc/SuSE-release" ] ; then
			dist_found="SUSE"
			log "INFO" "$(gettext "GNU/Linux Suse Distribution")"
		elif [ "$lsb_release" = "RedHatEnterpriseES" ] || \
			[ "$lsb_release" = "Fedora" ] || \
			[ -e "/etc/redhat-release" ] ; then
			dist_found="REDHAT"
			log "INFO" "$(gettext "GNU/Linux Redhat Distribution")"
		else
			dist_found="NOT_FOUND"
			log "INFO" "$(gettext "GNU/Linux distribution not found")"
			return 1
		fi
	elif [ "$system" = "FreeBSD" ] ; then
		dist_found="FREEBSD"
		log "INFO" "$(gettext "FreeBSD System")"
	elif [ "$system" = "AIX" ] ; then
		dist_found="AIX"
		log "INFO" "$(gettext "AIX System")"
	elif [ "$system" = "SunOS" ] ; then
		dist_found="SUNOS"
		log "INFO" "$(gettext "SunOS System")"
	else
		dist_found="NOT_FOUND"
		log "INFO" "$(gettext "System not found")"
	fi

	eval $distrib=$dist_found
	return 0
}

#----
## use this function to clean and exit centreon install
## This function use <@function purge_centreon_tmp_dir> function.
## TODO: Need to add fonctionnality 
##      - delete install file
##      - restore inital rigth
##      - ...
#----
function clean_and_exit() {
  local trap_sig=${1:-0}
  if [ $trap_sig -eq 0 ] ; then
    echo -e "$(gettext "\nTrap interrupt, Centreon'll exit now and clean install")"
    yes_no_default "$(gettext "Do you really want to quit Centreon install process ? ")" "$no"
    if [ $? -eq 1 ] ; then 
      echo "$(gettext "Continue...")"
      return 1
    fi
  fi
	log "EXIT" "$(gettext "Exit Centreon install")"
  [ -n "$SUDO_FILE" -a $upgrade -eq 0 ] && clean_sudo "$SUDO_FILE" 0
  purge_centreon_tmp_dir "silent"
	exit 1
}

#----
## Check space left for working directory
## @return 0	Space ok
## @return 1	No Space left
## @Globals	TMP_DIR
#----
function check_tmp_disk_space() {
	local min_space="35584"
	local free_space=""
	local tmp_dir=""

	tmp_dir=$(dirname $TMP_DIR)

	free_space=$(df -P $tmp_dir | tail -1 | awk '{print $4}')

	if [ "$free_space" -lt "$min_space" ] ; then
		echo_failure "$(gettext "No space left on tmp dir") : $tmp_dir  (<$min_space Ko)" "$fail"
		return 1
	else
		return 0
	fi
}

#----
## Ask to remove all temporaries working directory
## @param     silent option (silent)
## @return 0	remove done
## @return 1	don't remove (abort by user)
## @Globals	TMP_DIR, yes
#----
function purge_centreon_tmp_dir() {
	local silent="$1"
	local not_clean="1"
	local rc="0"
	while [ $not_clean -ne 0 ] ; do
		if [ "$silent" != "silent" ] ; then
  			yes_no_default "$(gettext "Do you want me to remove the centreon temporary working space to continue installation ?")" "$yes"
			rc=$?
		else
			rc=0
		fi
		if [ $rc -eq 0 ] ; then 
			local tmp_base_dir=`dirname $TMP_DIR`
			local tmp_dir=`basename $TMP_DIR`
			find $tmp_base_dir -name "$tmp_dir*" -type d \
				-exec rm -rf {} \; 2>/dev/null
			not_clean="0"
		else
			return 1
		fi
	done
	return 0
}

#----
## Clean sudoers file
## Generate a file without Centreon config. Need to have a BEGIN and END flags 
## file. After that, rewrite sudo file with clean file.
## @param	sudo file
## @param	0/1 to active a question to clean sudo (not by default)
## @Globals	TMP_DIR, LOG_FILE
#----
function clean_sudo() {
	local RC="1"
	local sudo_old="$1"
	local validate="${2:-0}"
  if [ ! -d "$TMP_DIR" ] ; then
    local sudo_clean="/tmp/sudo.clean"
  else
	  local sudo_clean="$TMP_DIR/sudo.clean"
  fi  
  
  if ! grep "CENTREON SUDO" $sudo_old &>/dev/null ; then 
    return 1
  fi

	${CAT} $sudo_old | \
	awk 'BEGIN { flag=0; }
	/^## BEGIN: CENTREON SUDO/ { flag=1; next; }
	/^## END: CENTREON SUDO/ { flag=0; next; }
	{ if (flag == 0) { print $0; } next; }' > $sudo_clean

	log "INFO" "$(gettext "New sudo file generate in:") $sudo_clean"
	if [ "$validate" -eq 1 ] ; then 
		yes_no_default "$(gettext "Do you want me to clean your sudo files ? (clean centreon config)")"
		RC="$?"
	fi
	if [ "$RC" -eq 0 -o "$validate" -eq 0 ] ; then 
		${CAT} $sudo_clean > $sudo_old 2>$LOG_FILE
		return 0
	fi
	return 0
}

#----
## Find file with macro in directory.
## @param	macro (separate with comma)
## @param 	directoty where to find
## @param	sub directory to find
## @param	file to search (possible to use pattern)
## @param	variable where define a list of file (temporaty file)
## @Globals	LOG_FILE, TMP_DIR
#----
function find_macros_in_dir() {
	local macro="$1"
	local src_dir="$2"
	local sub_dir="$3"
	local file="$4"
	local var_ref="$5"
	local file_out_tmp=""
	file_out_tmp=$(mktemp $TMP_DIR/file_out_tmp.XXXXXX)
	
	for mac in ${macro//,/ } ; do
		log "INFO" "$(gettext "Search file for macro") : $mac"
		( cd $src_dir ;
			find $sub_dir -mindepth 1 -type f -name "$file" | \
				xargs ${GREP} "$mac" | \
				cut -d: -f1 | \
				uniq >> "$file_out_tmp" 2>>"$LOG_FILE";
		)
	done

	eval $var_ref=$file_out_tmp
	return 0
}

#----
## Check result and print a message
## @param	return code to check
## @param	message to print
#----
function check_result() {
	local code=$1
	shift
	local message=$@

	if [ $code -eq 0 ] ; then
		echo_success "$message" "$ok"
	else
		echo_failure "$message" "$fail"
	fi
	return 0
}