#!/bin/sh

if [ "$1" = "configure" ] ; then

  if [ "$(getent passwd centreon)" ]; then

    chown -R centreon:centreon \
      /usr/share/centreon \
      /var/log/centreon \
      /var/lib/centreon
    chmod 0775 \
      /usr/share/centreon/src \
      /usr/share/centreon/api
    chmod -R 0775 \
      /var/log/centreon \
      /var/lib/centreon
    chmod -R 0775 \
      /usr/share/centreon/www \
      /usr/share/centreon/GPL_LIB/SmartyCache
    chmod 0664 \
      /usr/share/centreon/.env \
      /usr/share/centreon/.env.local.php
  fi

  # Replace macros ----
  sed -i "s#@PHP_BIN@#/usr/bin/php#g" /usr/share/centreon/bin/centreon
  sed -i "s#@PHP_BIN@#/usr/bin/php#g" /usr/share/centreon/bin/console
  sed -i "s#@PHP_BIN@#/usr/bin/php#g" /usr/share/centreon/bin/export-mysql-indexes
  sed -i "s#@PHP_BIN@#/usr/bin/php#g" /usr/share/centreon/bin/generateSqlLite
  sed -i "s#@PHP_BIN@#/usr/bin/php#g" /usr/share/centreon/bin/import-mysql-indexes

  chmod +x \
    /usr/share/centreon/bin/centFillTrapDB \
    /usr/share/centreon/bin/centreonSyncArchives \
    /usr/share/centreon/bin/centreonSyncPlugins \
    /usr/share/centreon/bin/centreon_trap_send \
    /usr/share/centreon/bin/export-mysql-indexes \
    /usr/share/centreon/bin/generateSqlLite \
    /usr/share/centreon/bin/import-mysql-indexes \
    /usr/share/centreon/bin/logAnalyserBroker \
    /usr/share/centreon/cron/centreon-backup.pl \
    /usr/share/centreon/cron/dashboardBuilder \
    /usr/share/centreon/cron/eventReportBuilder \
    /usr/share/centreon/vendor/enshrined/svg-sanitize/src/svg-scanner.php \
    /usr/share/centreon/www/install/tools/migration/logsMigration.pl


  if [ -f "/usr/bin/pear" ]; then
    /usr/bin/pear channel-update pear.php.net
    /usr/bin/pear install --force --alldeps db  >/dev/null
  fi


  if [ -f "/etc/init.d/cron" ]; then
      service cron restart
  fi

fi

# rebuild symfony cache on upgrade
if [ -n "$2" ]; then
  su - www-data -s /bin/bash -c "/usr/share/centreon/bin/console cache:clear --no-warmup"
fi

# Try auto configure timezone for php

timezone=$(/usr/bin/php -r '
  $timezoneName = timezone_name_from_abbr(trim(shell_exec("date \"+%Z\"")));
  if (preg_match("/Time zone: (\S+)/", shell_exec("timedatectl"), $matches)) {
    $timezoneName = $matches[1];
  }
  if (date_default_timezone_set($timezoneName) === false) {
    $timezoneName = "UTC";
  }
  echo $timezoneName;
' 2>/dev/null)
sed -i "s#^date.timezone = .*#date.timezone = ${timezone}#" /etc/php/8.0/mods-available/centreon.ini

exit 0
