centreon_security_authentication_login:
    methods: POST
    path: /providers/configurations/local
    controller: 'Core\Security\Authentication\Infrastructure\Api\Login\Local\LoginController'

centreon_security_authentication_login_openid:
    methods: GET
    path: /providers/configurations/openid
    controller: 'Core\Security\Authentication\Infrastructure\Api\Login\OpenId\LoginController'

centreon_security_authentication_logout:
    methods: POST
    path: /logout
    controller: 'Core\Security\Authentication\Infrastructure\Api\LogoutSession\LogoutSessionController'

centreon_security__renew_user_password:
    methods: PUT
    path: /users/{alias}/password
    controller: 'Core\Security\User\Infrastructure\Api\RenewPassword\RenewPasswordController'

centreon_security_authentication_websso_login:
    methods: GET
    path: /providers/configurations/web-sso
    controller: 'Core\Security\Infrastructure\Api\LoginWebSSOSession\LoginWebSSOSessionController'