Centreon\Application\PlatformTopology\PlatformTopologyHeliosFormat:
  properties:
    id:
      type: string
      groups: [platform_topology_helios]
    label:
      type: string
      groups: [platform_topology_helios]
    type:
      type: string
      groups: [platform_topology_helios]
    metadata:
      type: array
      groups: [platform_topology_helios]