Centreon\Application\Request\CheckRequest:
    properties:
        monitoringResources:
            type: array<Centreon\Domain\Monitoring\MonitoringResource\Model\MonitoringResource>
            serialized_name: 'resources'