name: Backend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  be-dependencies:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Cache Composer
      uses: actions/cache@v2
      id: composer-cache
      with:
        path: vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

    - name: Install composer dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

  be-phpcs:
    needs: be-dependencies

    runs-on: ubuntu-latest

    steps:

    - name: Cache Composer
      uses: actions/cache@v2
      id: composer-cache
      with:
        path: vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

    - name: Run phpcs
      uses: chekalsky/phpcs-action@v1
      with:
        phpcs_bin_path: './vendor/bin/phpcs'

