# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: frontend tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    #- run: npm run build --if-present
    - run: npm run eslint -- -o checkstyle-fe.xml -f checkstyle
    - uses: tinovyatkin/action-eslint@v1
      if: ${{ github.event_name == 'pull_request' }}
      with:
        repo-token: ${{secrets.GITHUB_TOKEN}}
        check-name: build # this is the check name from above 👆 where to post annotations
    - run: npm t -- --ci --reporters=jest-junit --runInBand
    - uses: actions/upload-artifact@v2
      with:
        name: junit-artifact
        path: junit.xml
