<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Rubber</name>
   <tag></tag>
   <elementGuidId>6fdd5d47-ace6-4bd3-83f6-3e426a9e2cfa</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>./img/icons/rub.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;graph_wrapper_331_3352&quot;)/div[@class=&quot;content&quot;]/div[@id=&quot;chart-legends-331_3352&quot;]/div[@class=&quot;chart-legend-action&quot;]/img[1]</value>
   </webElementProperties>
</WebElementEntity>
