<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Information</name>
   <tag></tag>
   <elementGuidId>2fbcf9c6-8479-4e50-a970-ef774015f957</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>./img/icons/info2.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;graph_wrapper_331_3353&quot;)/div[@class=&quot;content&quot;]/div[@id=&quot;chart-legends-331_3353&quot;]/div[@class=&quot;chart-legend-action&quot;]/img[2]</value>
   </webElementProperties>
</WebElementEntity>
