<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Last</name>
   <tag></tag>
   <elementGuidId>d03210e6-b7f2-4c8e-85fe-7fc98b1b2e92</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Last :</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;graph_wrapper_331_3353&quot;)/div[@class=&quot;content&quot;]/div[@id=&quot;chart-legends-331_3353&quot;]/div[@class=&quot;chart-legend&quot;]/div[@class=&quot;extra&quot;]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
